### ISSUE TITLE
Enhance pattern search spotlighting

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris_firefox#1125]
We currently support a test playback mode called "highlighting" that provides visual, on-screen graphics to show you real-time image searches that Iris is performing during test execution. Currently, this is implemented as a red outlined square (Mac/Win) or an opaque window with a cutout (Linux).

We'd like to move from the current "highlight" effect and do a "spotlight" effect instead, on all platforms. This will look more like what Linux has today. One exception - Linux has some limitations around transparent graphics, so currently, the effect makes the background graphics a little hard to see.

@silviuFlorin seems to think we can find a cross-platform solution to overlay a partially-opaque image on the screen, with a cutout over the area we want to show - the "spotlight" effect.

**Comment by mwobensmith** [comment]
Also, once we have this, change all mentions of "highlight" in the code to "spotlight" for consistency.

**Comment by mwobensmith** [comment]
Looking at the work in progress, I see two things.

* We will have to install `wxPython` via pip.
* The `spotlight_test.py` looks good on Windows. On Mac, it gives me an error:

```
This program needs access to the screen. Please run with a
Framework build of python, and only when you are logged in
on the main display of your Mac.
```

From what I understand, framework builds of Python are not the same as what is installed on Mac by default. Not sure how to solve, unless we install a framework build of Python with Iris.

**Comment by mwobensmith** [comment]
Moving to post-1.0. Need a more creative solution to this problem post-release.

**Comment by mwobensmith** [comment]
Not exactly a "spotlight" but here's an example of animated outlines, changing size/alpha.

![spotlight](https://user-images.githubusercontent.com/3019057/48450022-635dd700-e759-11e8-9cc3-bf2f00059a59.gif)

**Comment by tracywalker** [comment]
Yes, this is better than the thin static wire frame around pattern matches. I liked Spotlight better, but this would do fine.
