### ISSUE TITLE
Iris fails to run on Mac cron job

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris_firefox#1381]
I believe this is due to `mss` and use of `ctypes`, but I'll let @mariusandreifilip handle this.

**Comment by mariusandreifilip** [comment]
The difference between MSS and pyautogui is that Mss use ctypes to create screenshots and pyautogui a terminal command and in a crontab environment the use of a native os(X11) library is considered a security violation and is not permitted.
The alternative to crontabs is a launch deamon that bypasses the security layer of the system.The disadvantage of using a daemon is the stability and the lack of control .

The easiest way to create system agent(daemon) is to use Lingon it's a freeware software that help you create the .plist file that looks like this:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>iriscron</string>
	<key>OnDemand</key>
	<true/>
	<key>ProgramArguments</key>
	<array>
		<string>/Users/mozilla/cronjob.sh</string>
	</array>
	<key>QueueDirectories</key>
	<array>
		<string>/Users/mozilla/cronjob.sh</string>
	</array>
	<key>StartCalendarInterval</key>
	<dict>
		<key>Hour</key>
		<integer>13</integer>
		<key>Minute</key>
		<integer>58</integer>
	</dict>
</dict>
</plist>
 and also loads it into the system.
Another solution is to create the xml file by hand and load it with **launchd**
Here you can find more info related to [launchd](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLaunchdJobs.html)
