### ISSUE TITLE
Rename internal classes to get rid of old design pattern

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris_firefox#1412]
We instituted a design pattern a while ago where we created an object from an internal class, in order to simulate static members.

`Settings = _IrisSettings()`

This was during a period of code migration. It allowed us to change some underlying logic while keeping the public API the same.

Now that we have stabilized the code, we need to get rid of this notion by rewriting these internal classes with normal names, with static methods/properties.

This will greatly help our documentation, which currently looks odd because of this convention. We should do this to `_IrisSettings` and `_IrisProfile`. Care should be taken to name/document internal/external APIs as such.

**Comment by tracywalker** [comment]
Matt, is this something that remains to be done?

**Comment by mwobensmith** [comment]
This is not an issue in `iris_firefox` anymore.
