### ISSUE TITLE
Fix remove_tags_from_a_bookmark intermittent failure

### ISSUE THREAD

**Issue by IonutBudeanu** [mozilla/iris_firefox#1525]
`remove_tags_from_a_bookmark` test is failing because of an while block that has too few tries. Due to differences between platforms the while block starts from different focused points,  sometimes 5 attempts are not enough for a correct focus on the searched pattern. 

Fix - increase `max_attempts` variable to 10.

**Comment by pavelciapa** [comment]
Fails on osx and linux after line 60

**Comment by dbakaev** [comment]
Fails on win7

**Comment by ranjit-exalt** [comment]
Moving it to "Done" as pull request #4261 is merged in dev.
