### ISSUE TITLE
Error is thrown in the console after refreshing the Control Center page

### ISSUE THREAD

**Issue by icrisan** [mozilla/iris_firefox#1528]
Steps to reproduce:
1. Open the Iris Control Center(by running the iris command from the terminal)
2. Refresh the page

Expected results:
The Control Center page is successfully refreshed.

Actual results:
Blank page is displayed after page refresh. 
The following error is thrown in the console: "The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol."

**Comment by icrisan** [comment]
<img width="1433" alt="screen shot 2018-11-27 at 2 42 47 pm" src="https://user-images.githubusercontent.com/30526045/49083574-ac338680-f255-11e8-93e2-a4d2cc2651fe.png">

**Comment by psilaghi** [comment]
I'm not able to reproduce locally.
So, probably a server side issue?

**Comment by mwobensmith** [comment]
https://github.com/mozilla/iris/issues/450
