### ISSUE TITLE
Add support for running tests on specific firefox version in Control Center

### ISSUE THREAD

**Issue by rrobotin** [mozilla/iris_firefox#1645]
Add in the Firefox version picker, the ability to choose the latest release candidate build using the '-f' argument from the command line and

**Comment by mwobensmith** [comment]
Hi @rrobotin, can you clarify this a little bit?

* The Control Center already has the ability to download the latest release candidate by choosing "latest" in the drop-down menu. Do we need to add something more to this menu?

* Are you requesting enhancements to the command-line argument `-f` ?
