### ISSUE TITLE
Test case: Remove a bookmark using star-shaped button

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris_firefox#2069]
https://testrail.stage.mozaws.net/index.php?/cases/view/163407

**Comment by hathibelagal-dev** [comment]
@tracywalker I'd like to work on a few more tests. Can I take this?

**Comment by tracywalker** [comment]
Yes,  here are this test case steps.


  | Step | Expected Result
-- | -- | --
1 | Launch Firefox. | Firefox is successfully launched.
2 | Open a website that's currently in your Bookmarks list. | The website is properly loaded.
3 | Click the star-shaped button. | Edit This Bookmark panel is displayed under the star-shaped button.
4 | Click on Remove Bookmark. | The star-shaped button changes its color to white.
