### ISSUE TITLE
Fix bookmarks_toolbar_sorted_by_name test case

### ISSUE THREAD

**Issue by IonutBudeanu** [mozilla/iris_firefox#2293]
`bookmarks_toolbar_sorted_by_name ` test is failing due to a deprecated pocket pattern. Changing the pattern will fix the test.

**Comment by pavelciapa** [comment]
Failed due to pattern `toolbar_bookmarks_sorted_by_name.png`

**Comment by dbakaev** [comment]
Unstable on linux, win7
