### ISSUE TITLE
fix resizing_browser_window test case

### ISSUE THREAD

**Issue by nevdokimov** [mozilla/iris_firefox#2319]
fix resizing_browser_window test case

**Comment by nevdokimov** [comment]
> Status: Can't reproduce

Details: Can not reproduce failure described at step: "The browser window is successfully resized. - [Actual]: False [Expected]: True" for OSX with the following stacktrace:

>> Traceback (most recent call last):
>> File "/Users/admin/.local/share/virtualenvs/iris-edWfnQv0/bin/iris", line 11, in
>> load_entry_point('iris', 'console_scripts', 'iris')()
>> File "/Users/admin/iris/iris/__main__.py", line 38, in main
>> run_iris()
>> File "/Users/admin/iris/iris/__main__.py", line 108, in run_iris
>> run(master_test_list, tests, browser)
>> File "/Users/admin/iris/iris/test_runner.py", line 69, in run
>> current.run()
>> File "/Users/admin/iris/iris/tests/content_scroll/resizing_browser_window.py", line 37, in run
>> assert_true(self, resizing_confirmed_exists, 'The browser window is successfully resized.')
>> File "/Users/admin/iris/iris/asserts.py", line 78, in assert_true
>> assert_equal(test_case, actual, True, message)
>> File "/Users/admin/iris/iris/asserts.py", line 32, in assert_equal
>> Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))

**Comment by pavelciapa** [comment]
Fails on Linux due to VM bug, OS bug

investigate chance of **fx-bug**
