### ISSUE TITLE
Fix scroll_each_window test case

### ISSUE THREAD

**Issue by pavelciapa** [mozilla/iris_firefox#2336]

**Comment by pavelciapa** [comment]
Fails intermittently on different steps
6:15:10 PM
#1 Iris tab available
6:15:41 PM
#2 Browser console opened.
6:15:43 PM
#3 Value entered in browser console.
6:15:50 PM
#4 Firefox tab loaded
6:15:50 PM
#5 Firefox tab is active.
6:15:56 PM
#6 Focus tab loaded
6:15:57 PM
#7 Focus site tab is active.
6:16:01 PM
#8 Focus tab dragged.
6:16:01 PM
#9 Focus tab dropped.
6:16:02 PM
#10 Focus content before scrolling is on the page.
6:16:05 PM
#11 Focus tab scrolled successful.
6:16:08 PM
#12 Firefox tab dragged.
6:16:20 PM
#13 Firefox tab dropped. - [Actual]: False [Expected]: True

**Comment by pavelciapa** [comment]
Can not reproduce failure described at step: "Firefox tab dropped. - [Actual]: False [Expected]: True" for Linux with the following stacktrace:

>> Traceback (most recent call last):                                                                     
>>   File "/home/svuser/.local/share/virtualenvs/iris-zpGrSWP0/bin/iris", line 11, in <module>            
>>     load_entry_point('iris', 'console_scripts', 'iris')()                                              
>>   File "/home/svuser/iriscron/iris/iris/__main__.py", line 38, in main                                 
>>     run_iris()                                                                                         
>>   File "/home/svuser/iriscron/iris/iris/__main__.py", line 108, in run_iris                            
>>     run(master_test_list, tests, browser)                                                              
>>   File "/home/svuser/iriscron/iris/iris/test_runner.py", line 69, in run                               
>>     current.run()                                                                                      
>>   File "/home/svuser/iriscron/iris/iris/tests/session_restore/scroll_each_window.py", line 121, in run 
>>     assert_true(self, firefox_tab_dropped, 'Firefox tab dropped.')                                     
>>   File "/home/svuser/iriscron/iris/iris/asserts.py", line 78, in assert_true                           
>>     assert_equal(test_case, actual, True, message)                                                     
>>   File "/home/svuser/iriscron/iris/iris/asserts.py", line 32, in assert_equal                          
>>     Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))

**Comment by tracywalker** [comment]
This is still failing in recent test runs
