### ISSUE TITLE
Fix middle_clicking_search_results_open_new_tab

### ISSUE THREAD

**Issue by pavelciapa** [mozilla/iris_firefox#2549]
middle_clicking_search_results_open_new_tab - Middle clicking search results does not open a new tab.                                 By: icrisan
--
1 | 6:34:41 AM | 019-03-18 06:34:41,890 [ERROR] [iris.test_case] >>> ERROR <<< Error encountered in test

**Comment by tracywalker** [comment]
This test is failing in daily runs trying to find the search bar magnifying glass. Try 0.7 similarity.  Then the test fails to middle click a search suggestion.  It appears to be middle clicking the search term in the search bar.

Please investigate and fix.
