### ISSUE TITLE
fix not_crash_options_enabled test case

### ISSUE THREAD

**Issue by nevdokimov** [mozilla/iris_firefox#2588]
Win, Win7, Linux, OSX.
Windows 10

not_crash_options_enabled - Firefox does not crash - all antivirus options enabled.                                 
--
1 | 7:18:32 PM | Youtube is properly loaded
2 | 7:18:33 PM | The video is properly loaded and displayed.
3 | 7:18:37 PM | Soundcloud is properly loaded
4 | 7:18:47 PM | The sound is properly loaded and played. - [Actual]: False [Expected]: True

**Comment by yeyartsev** [comment]
Cannot reproduce failure on step "Add Firefox Multi-Account Containers? pop-up displayed - [Actual]: False [Expected]: True"
