### ISSUE TITLE
Fix the "open_url_in_tab" test case

### ISSUE THREAD

**Issue by icrisan** [mozilla/iris_firefox#2669]

**Comment by tracywalker** [comment]
Why doesn't this test case use change_preference() helper?

**Comment by icrisan** [comment]
@tracywalker to be honest I don't remember why. This test case was approved by you, maybe we talked abut this approach or maybe not. I really don't remember. If you want I can update the test case to use change_preference() helper.

**Comment by tracywalker** [comment]
The test case may have been created before the helper?  Anyway, yes, please update it to use the helper, thank you.

**Comment by tracywalker** [comment]
code approved

**Comment by spronoza** [comment]
Reopened due to UI changes
