### ISSUE TITLE
Implement API: drag() (Region method)

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris_firefox#267]

**Comment by tracywalker** [comment]
http://doc.sikuli.org/region.html?highlight=drag#Region.drag

sikuli implemented drag and drop as separate operations.  

I can think of a test case that checks that an interrupted drag operation snaps the dragged item back to its original location.  We can't make such a test with our implementation.  However,  I don't think that makes this a 1.0.  We can DnD fine with drag_drop.
