### ISSUE TITLE
Fix new_separartor_other_bookmarks test

### ISSUE THREAD

**Issue by yeyartsev** [mozilla/iris_firefox#2677]
Test failed on step 1: 
Firefox menu is opened - [Actual]: False [Expected]: True 
 against win10 with traceback:
>> Traceback (most recent call last):
>> File "C:\Users\svuser\.virtualenvs\iris-NcrgrEXF\Scripts\iris-script.py", line 11, in
>> load_entry_point('iris', 'console_scripts', 'iris')()
>> File "c:\iriscron2\iris\iris\__main__.py", line 38, in main
>> run_iris()
>> File "c:\iriscron2\iris\iris\__main__.py", line 108, in run_iris
>> run(master_test_list, tests, browser)
>> File "c:\iriscron2\iris\iris\test_runner.py", line 69, in run
>> current.run()
>> File "c:\iriscron2\iris\iris\tests\bookmark\new_separartor_other_bookmarks.py", line 32, in run
>> assert_true(self, firefox_menu_opened, 'Firefox menu is opened')
>> File "c:\iriscron2\iris\iris\asserts.py", line 78, in assert_true
>> assert_equal(test_case, actual, True, message)
>> File "c:\iriscron2\iris\iris\asserts.py", line 32, in assert_equal
>> Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))

**Comment by yeyartsev** [comment]
Cannot reproduce

**Comment by pavelciapa** [comment]
Test is passing in recent test runs and can be closed.
