### ISSUE TITLE
Browser console title not found for osx

### ISSUE THREAD

**Issue by yeyartsev** [mozilla/iris_firefox#2682]
Pattern browser_console_title.png wasn't found during running drag_drop_html test

>> Traceback (most recent call last):
>> File "/Users/admin/.local/share/virtualenvs/iris-edWfnQv0/bin/iris", line 11, in
>> load_entry_point('iris', 'console_scripts', 'iris')()
>> File "/Users/admin/iris/iris/__main__.py", line 38, in main
>> run_iris()
>> File "/Users/admin/iris/iris/__main__.py", line 108, in run_iris
>> run(master_test_list, tests, browser)
>> File "/Users/admin/iris/iris/test_runner.py", line 69, in run
>> current.run()
>> File "/Users/admin/iris/iris/tests/drag_and_drop/drag_drop_html.py", line 54, in run
>> assert_true(self, console_opened, 'Browser console is opened')
>> File "/Users/admin/iris/iris/asserts.py", line 78, in assert_true
>> assert_equal(test_case, actual, True, message)
>> File "/Users/admin/iris/iris/asserts.py", line 32, in assert_equal
>> Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))

**Comment by yeyartsev** [comment]
Cannot reproduce

**Comment by tracywalker** [comment]
This was reported as failing against OSX.  Does it still fail there?  I haven't received any email reports for OSX lately.

**Comment by tracywalker** [comment]
Fails for me locally on OSX.

**Comment by tracywalker** [comment]
This test hasn't failed in the past week on all platforms.
