### ISSUE TITLE
Investigate why download_manager test failure causes entire test run failure

### ISSUE THREAD

**Issue by pavelciapa** [mozilla/iris_firefox#2688]
Test page loading files from external website failure is somehow causing entire test run failure.

Test run of download_manager test case failure causing for that. Described at #2610 

![2019_03_27_21_15_28_242538_about_downloads_accurate_data](https://user-images.githubusercontent.com/45387203/55164803-021d2a00-5175-11e9-8cb7-b7049a7b8920.jpg)
![2019_03_27_21_15_29_175788_about_downloads_accurate_data_not_found](https://user-images.githubusercontent.com/45387203/55164805-02b5c080-5175-11e9-8e9e-fa781cbe596a.jpg)
![2019_03_27_21_15_30_197434_about_downloads_accurate_data_not_found](https://user-images.githubusercontent.com/45387203/55164806-02b5c080-5175-11e9-90f9-9bd0d624098a.jpg)

_Originally posted by @pavelciapa in https://github.com/mozilla/iris/issues/2610#issuecomment-477615848_

**Comment by pavelciapa** [comment]
Test run stops on test from donwload_manager suite and when opening console typing **[B^[** continiously, without closing Firefox and starting next test.

> 2019-05-09 00:03:52,574 [INFO] [iris.test_runner] Executing: 243 - [downloads_button_works_properly_positioned_in_the_tabs_bar]: The downloads button works properly positioned in the tabs bar.
> 2019-05-09 00:04:11,843 [SUCCESS] [iris.test_case] >>> PASSED <<< Step 1: Download button is available.
> 2019-05-09 00:04:16,965 [SUCCESS] [iris.test_case] >>> PASSED <<< Step 2: Custom Download button is available in tabs bar.
> [B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^C
> 
> Process Process-1:
> Traceback (most recent call last):
>   File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
>     self.run()
>   File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
>     self._target(*self._args, **self._kwargs)
>   File "/Users/ciapa/iris/iris/local_web_server.py", line 127, in __init__
>     self.start()
>   File "/Users/ciapa/iris/iris/local_web_server.py", line 146, in start
>     httpd.handle_request()
>   File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 274, in handle_request
>     fd_sets = _eintr_retry(select.select, [self], [], [], timeout)
>   File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
>     return func(*args)
> KeyboardInterrupt


Attaching full log
[iris_log.log](https://github.com/mozilla/iris/files/3165346/iris_log.log)

**Comment by pavelciapa** [comment]
In another test run on remote OSX machine download_manager test case failed test run. 
Test run stoped throwing an error:
Full log: [iris_log.log](https://github.com/mozilla/iris/files/3165380/iris_log.log)


> ------------------------------------------------------------------------------------------------------------------------
> 2019-05-08 14:50:26 [INFO] [iris.test_runner] Executing: 243 - [downloads_button_works_properly_positioned_in_the_tabs_bar]: The downloads button works properly positioned in the tabs bar.
> 2019-05-08 14:50:47 [SUCCESS] [iris.test_case] >>> PASSED <<< Step 1: Download button is available.
> 2019-05-08 14:50:53 [SUCCESS] [iris.test_case] >>> PASSED <<< Step 2: Custom Download button is available in tabs bar.
> Traceback (most recent call last):
>   File "/Users/admin/.local/share/virtualenvs/iris-1ZsGZN8u/bin/iris", line 11, in <module>
>     load_entry_point('iris', 'console_scripts', 'iris')()
>   File "/Users/admin/PycharmProjects/iris/iris/__main__.py", line 38, in main
>     run_iris()
>   File "/Users/admin/PycharmProjects/iris/iris/__main__.py", line 108, in run_iris
>     run(master_test_list, tests, browser)
>   File "/Users/admin/PycharmProjects/iris/iris/test_runner.py", line 69, in run
>     current.run()
>   File "/Users/admin/PycharmProjects/iris/iris/tests/download_manager/downloads_button_works_properly_positioned_in_the_tabs_bar.py", line 51, in run
>     download_file(pattern, DownloadFiles.OK)
>   File "/Users/admin/PycharmProjects/iris/iris/api/helpers/download_manager_utils.py", line 161, in download_file
>     click(file_to_download)
>   File "/Users/admin/PycharmProjects/iris/iris/api/core/mouse.py", line 77, in click
>     _general_click(where, 1, duration, in_region, 'left')
>   File "/Users/admin/PycharmProjects/iris/iris/api/core/mouse.py", line 298, in _general_click
>     _click_pattern(where, clicks, duration, in_region, button)
>   File "/Users/admin/PycharmProjects/iris/iris/api/core/mouse.py", line 270, in _click_pattern
>     p_top = positive_image_search(pattern=pattern, region=in_region)
>   File "/Users/admin/PycharmProjects/iris/iris/api/core/util/image_search.py", line 264, in positive_image_search
>     if is_multiprocessing_enabled():
>   File "/Users/admin/PycharmProjects/iris/iris/api/core/util/core_helper.py", line 74, in is_multiprocessing_enabled
>     return multiprocessing.cpu_count() >= MIN_CPU_FOR_MULTIPROCESSING and get_os() != 'win'
>   File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/__init__.py", line 123, in cpu_count
>     with os.popen(comm) as p:
> OSError: [Errno 35] Resource temporarily unavailable

**Comment by tracywalker** [comment]
Related issue #3234

**Comment by tracywalker** [comment]
Download test failures are being addressed in new issues.
