### ISSUE TITLE
Fix history_not_remembered

### ISSUE THREAD

**Issue by pavelciapa** [mozilla/iris_firefox#2703]
Fails on different steps, presumably because of short timeouts < 5 seconds

history_not_remembered - History is not remembered if reopening a Private window from the dock (for a profile used only in private mode)
6:40:24,603 [ERROR] [iris.test_case] >>> ERROR <<< Error encountered in test

**Comment by spronoza** [comment]
@tracywalker This test was blocked by issue_400 and excluded for Win and Linux platform because it is Mac specific. Now there is no "blocked_by"  and "exclude" is commented in the commit fa28c86981dd91a83ba9c2e409d0059b5daa41df. What should we do with this?

**Comment by tracywalker** [comment]
Hmmm, test still fails on again on Mac.  I must have made a mistake here.  Do you have a fix? If so please implement it. Also please re-enable the `exclude=[OSPlatform.WINDOWS, OSPlatform.LINUX]' statement.  I missed that this test is for MAC only. Sorry about that.

**Comment by pavelciapa** [comment]
Step 4 says
`Click on the Firefox icon.` (from the Dock panel)

Dock icons size is changing dynamicly, I will add tag Heisenbug, as we can't set some default size icon, or after setting it can change when adding/removing icons in Dock panel during work. 

Unless we add precondition to set certain defaults for Dock size

**Comment by pavelciapa** [comment]
> Default is just left of center.

when we set slider, magnification off, then icon sizes will be changed anyway, if more icons appeared in Dock

same slider settings, different sizes:

![image](https://user-images.githubusercontent.com/45387203/63788787-9981d700-c8e5-11e9-8edd-a22129fba499.png)
![image](https://user-images.githubusercontent.com/45387203/63788805-9f77b800-c8e5-11e9-9f3c-8f9d9e3f3ee1.png)

**Comment by pavelciapa** [comment]
yep, Dock is shrinking by itself

**Comment by pavelciapa** [comment]
Block by `issue_3220`
