### ISSUE TITLE
External web-pages issues

### ISSUE THREAD

**Issue by spronoza** [mozilla/iris_firefox#2754]
External web-page was downloading too long

**Comment by spronoza** [comment]
The failure is still reproducible for Linux

**Comment by spronoza** [comment]
The failure is reproducible for data_after_shutdown

**Comment by nevdokimov** [comment]
The failure is still reproducible for no_navigation_issues

**Comment by nevdokimov** [comment]
The failure is still reproducible for sites_loaded_5_tabs_dont_crash

**Comment by tracywalker** [comment]
We'll be addressing any current download test failures in new issues.
