### ISSUE TITLE
Fix open_all_bookmarks_from_most_visited_section test

### ISSUE THREAD

**Issue by spronoza** [mozilla/iris_firefox#2761]
The test fails at step: "The website #8 from 'Most Visited' section is opened - [Actual]: False [Expected]: True" for OSX with the following stacktrace:
-------
>> Traceback (most recent call last):                                                                            
>>   File "/Users/dev/.local/share/virtualenvs/iris-GK6srotc/bin/iris", line 11, in <module>                     
>>     load_entry_point('iris', 'console_scripts', 'iris')()                                                     
>>   File "/Users/dev/iris/iris/__main__.py", line 38, in main                                                   
>>     run_iris()                                                                                                
>>   File "/Users/dev/iris/iris/__main__.py", line 108, in run_iris                                              
>>     run(master_test_list, tests, browser)                                                                     
>>   File "/Users/dev/iris/iris/test_runner.py", line 69, in run                                                 
>>     current.run()                                                                                             
>>   File "/Users/dev/iris/iris/tests/bookmark/open_all_bookmarks_from_most_visited_section.py", line 68, in run 
>>     assert_true(self, site_from_list_opened, 'The website #' + str(num) + ' from \'Most Visited\' '           
>>   File "/Users/dev/iris/iris/asserts.py", line 78, in assert_true                                             
>>     assert_equal(test_case, actual, True, message)                                                            
>>   File "/Users/dev/iris/iris/asserts.py", line 32, in assert_equal                                            
>>     Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))

**Comment by pavelciapa** [comment]
Outdated pattern for search engine icon
