### ISSUE TITLE
Fix key_navigation_high_contrast_theme test

### ISSUE THREAD

**Issue by pavelciapa** [mozilla/iris_firefox#2771]
Can not reproduce failure described at step: "The 'Wikipedia' one-off button is highlighted. - [Actual]: False [Expected]: True" for OSX with the following stacktrace:
-
>> Traceback (most recent call last):                                                                      
>>   File "/Users/admin/.local/share/virtualenvs/iris-edWfnQv0/bin/iris", line 11, in <module>             
>>     load_entry_point('iris', 'console_scripts', 'iris')()                                               
>>   File "/Users/admin/iris/iris/__main__.py", line 38, in main                                           
>>     run_iris()                                                                                          
>>   File "/Users/admin/iris/iris/__main__.py", line 108, in run_iris                                      
>>     run(master_test_list, tests, browser)                                                               
>>   File "/Users/admin/iris/iris/test_runner.py", line 69, in run                                         
>>     current.run()                                                                                       
>>   File "/Users/admin/iris/iris/tests/awesomebar/key_navigation_high_contrast_theme.py", line 75, in run 
>>     assert_true(self, expected, 'The \'Wikipedia\' one-off button is highlighted.')                     
>>   File "/Users/admin/iris/iris/asserts.py", line 78, in assert_true                                     
>>     assert_equal(test_case, actual, True, message)                                                      
>>   File "/Users/admin/iris/iris/asserts.py", line 32, in assert_equal                                    
>>     Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))

**Comment by tracywalker** [comment]
This test case is reported as failing in nightly test runs on all platforms.

**Comment by pavelciapa** [comment]
Asked question to test updater - A. Valda

**Comment by pavelciapa** [comment]
This is to be blocked as it has _**OS high contrast theme**_

**Comment by pavelciapa** [comment]
![image](https://user-images.githubusercontent.com/45387203/62366369-2ec3c280-b516-11e9-84b6-b23630f255f5.png)

**Comment by tracywalker** [comment]
I'll remove the test from our test suite.
