### ISSUE TITLE
Fix pdf_viewer test

### ISSUE THREAD

**Issue by nevdokimov** [mozilla/iris_firefox#2772]
Can not reproduce failure described at step: "Presentation Mode is successfully enabled - [Actual]: False [Expected]: True" for OSX with the following stacktrace:

>> Traceback (most recent call last):                                                                     
>>   File "/Users/admin/.local/share/virtualenvs/iris-edWfnQv0/bin/iris", line 11, in <module>            
>>     load_entry_point('iris', 'console_scripts', 'iris')()                                              
>>   File "/Users/admin/iris/iris/__main__.py", line 38, in main                                          
>>     run_iris()                                                                                         
>>   File "/Users/admin/iris/iris/__main__.py", line 108, in run_iris                                     
>>     run(master_test_list, tests, browser)                                                              
>>   File "/Users/admin/iris/iris/test_runner.py", line 69, in run                                        
>>     current.run()                                                                                      
>>   File "/Users/admin/iris/iris/tests/content_scroll/pdf_viewer.py", line 57, in run                    
>>     assert_true(self, presentation_mode_enabled_exists, 'Presentation Mode is successfully enabled')   
>>   File "/Users/admin/iris/iris/asserts.py", line 78, in assert_true                                    
>>     assert_equal(test_case, actual, True, message)                                                     
>>   File "/Users/admin/iris/iris/asserts.py", line 32, in assert_equal                                   
>>     Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))

**Comment by pavelciapa** [comment]
Test is passing in recent test runs and can be closed.
