### ISSUE TITLE
Fix tracking_protection_deactivated test

### ISSUE THREAD

**Issue by pavelciapa** [mozilla/iris_firefox#2776]
Default checkbox is different after Firefox update. Change pattern to fix this

The test fails at step: "The Content blocking shield is not displayed near the address bar. - [Actual]: True [Expected]: False" for OSX with the following stacktrace:
----
>> Traceback (most recent call last):                                                                         
>>   File "/Users/admin/.local/share/virtualenvs/iris-edWfnQv0/bin/iris", line 11, in <module>                
>>     load_entry_point('iris', 'console_scripts', 'iris')()                                                  
>>   File "/Users/admin/iris/iris/__main__.py", line 38, in main                                              
>>     run_iris()                                                                                             
>>   File "/Users/admin/iris/iris/__main__.py", line 108, in run_iris                                         
>>     run(master_test_list, tests, browser)                                                                  
>>   File "/Users/admin/iris/iris/test_runner.py", line 69, in run                                            
>>     current.run()                                                                                          
>>   File "/Users/admin/iris/iris/tests/private_browsing/tracking_protection_deactivated.py", line 72, in run 
>>     'The Content blocking shield is not displayed near the address bar.')                                  
>>   File "/Users/admin/iris/iris/asserts.py", line 89, in assert_false                                       
>>     assert_equal(test_case, actual, False, message)                                                        
>>   File "/Users/admin/iris/iris/asserts.py", line 32, in assert_equal                                       
>>     Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))

**Comment by tracywalker** [comment]
This is still failing and currently blocked_by issue_402  (which is not the right issue)
