### ISSUE TITLE
Fix delete_cookies_when_closing test

### ISSUE THREAD

**Issue by spronoza** [mozilla/iris_firefox#2789]
Can not reproduce failure described at step: "The manage data button exists. - [Actual]: False [Expected]: True" for OSX with the following stacktrace:

>> Traceback (most recent call last):                                                                     
>>   File "/Users/admin/.local/share/virtualenvs/iris-edWfnQv0/bin/iris", line 11, in <module>            
>>     load_entry_point('iris', 'console_scripts', 'iris')()                                              
>>   File "/Users/admin/iris/iris/__main__.py", line 38, in main                                          
>>     run_iris()                                                                                         
>>   File "/Users/admin/iris/iris/__main__.py", line 108, in run_iris                                     
>>     run(master_test_list, tests, browser)                                                              
>>   File "/Users/admin/iris/iris/test_runner.py", line 69, in run                                        
>>     current.run()                                                                                      
>>   File "/Users/admin/iris/iris/tests/privacy/delete_cookies_when_closing.py", line 66, in run          
>>     assert_true(self, manage_data_button_exists, 'The manage data button exists.')                     
>>   File "/Users/admin/iris/iris/asserts.py", line 78, in assert_true                                    
>>     assert_equal(test_case, actual, True, message)                                                     
>>   File "/Users/admin/iris/iris/asserts.py", line 32, in assert_equal                                   
>>     Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))

**Comment by spronoza** [comment]
Reproduced and fixed

**Comment by pavelciapa** [comment]
Fails on win7 due to new UI
Update pattern for all OSs
![image](https://user-images.githubusercontent.com/45387203/63500993-650fb480-c4ba-11e9-8256-edb564b4a69a.png)

prosport_cookies.png
![image](https://user-images.githubusercontent.com/45387203/63501021-6e008600-c4ba-11e9-8fd6-99d935562d87.png)

**Comment by pavelciapa** [comment]
In this test cookies size differs on Win7,win10 to osx, linux. @tracywalker, is this a bug?

the difference is win shows site with 0 kbs of cache, and osx doesn't show a site.

![изображение](https://user-images.githubusercontent.com/45387203/63501801-d308ab80-c4bb-11e9-985d-76666197b076.png)
