### ISSUE TITLE
Fix user_is_able_to_add_new_search_engines test

### ISSUE THREAD

**Issue by spronoza** [mozilla/iris_firefox#2803]
The test fails at step: "The 'Google Play' search engine is added to Firefox. - [Actual]: False [Expected]: True" for Linux with the following stacktrace:

>> Traceback (most recent call last):                                                                     
>>   File "/home/user/.local/share/virtualenvs/iris-s-cvVCBB/bin/iris", line 11, in <module>              
>>     load_entry_point('iris', 'console_scripts', 'iris')()                                              
>>   File "/home/user/iris/iris/__main__.py", line 38, in main                                            
>>     run_iris()                                                                                         
>>   File "/home/user/iris/iris/__main__.py", line 108, in run_iris                                       
>>     run(master_test_list, tests, browser)                                                              
>>   File "/home/user/iris/iris/test_runner.py", line 69, in run                                          
>>     current.run()                                                                                      
>>   File "/home/user/iris/iris/tests/search/user_is_able_to_add_new_search_engines.py", line 101, in run 
>>     assert_true(self, expected, 'The \'Google Play\' search engine is added to Firefox.')              
>>   File "/home/user/iris/iris/asserts.py", line 78, in assert_true                                      
>>     assert_equal(test_case, actual, True, message)                                                     
>>   File "/home/user/iris/iris/asserts.py", line 32, in assert_equal                                     
>>     Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))

**Comment by pavelciapa** [comment]
Seems that Google Play icon is not loading correctly. 
Adding timeout and new pattern to fix this
![photo_2019-04-22_15-45-43](https://user-images.githubusercontent.com/45387203/56500985-b2344780-6515-11e9-986b-857d75e4b180.jpg)

**Comment by pavelciapa** [comment]
- Unfocus search engine icon

![изображение](https://user-images.githubusercontent.com/45387203/65415647-aced6880-dde5-11e9-8879-41cd7992b606.png)
