### ISSUE TITLE
Fix find_nonexistent_string for win7

### ISSUE THREAD

**Issue by yeyartsev** [mozilla/iris_firefox#2827]
Test fails against win7 with traceback :

>> Traceback (most recent call last):                                                            << 
>>   File "c:\iris\iris\test_runner.py", line 69, in run                                         << 
>>     current.run()                                                                             << 
>>   File "c:\iris\iris\tests\find_toolbar\find_nonexistent_string.py", line 48, in run          << 
>>     click(FindToolbar.FIND_PREVIOUS)                                                          << 
>>   File "c:\iris\iris\api\core\mouse.py", line 77, in click                                    << 
>>     _general_click(where, 1, duration, in_region, 'left')                                     << 
>>   File "c:\iris\iris\api\core\mouse.py", line 298, in _general_click                          << 
>>     _click_pattern(where, clicks, duration, in_region, button)                                << 
>>   File "c:\iris\iris\api\core\mouse.py", line 273, in _click_pattern                          << 
>>     raise FindError('Unable to click on: %s' % pattern.get_file_path())                       << 
>> FindError: Unable to click on: c:\iris\iris\api\core\firefox_ui\images\win7\find_previous.png <<

**Comment by pavelciapa** [comment]
Close as duplicate https://github.com/mozilla/iris_firefox/issues/2830
