### ISSUE TITLE
Fix settings_browser_level test

### ISSUE THREAD

**Issue by nevdokimov** [mozilla/iris_firefox#2831]
Can not reproduce failure described at step: "The value is changed to 50 - [Actual]: False [Expected]: True" for Win 10 with the following stacktrace:

>> Traceback (most recent call last):                                                                     
>>   File "C:\Users\evdokimov\.virtualenvs\iris-oX-b2_9c\Scripts\iris-script.py", line 11, in <module>    
>>     load_entry_point('iris', 'console_scripts', 'iris')()                                              
>>   File "d:\iris\iris\__main__.py", line 38, in main                                                    
>>     run_iris()                                                                                         
>>   File "d:\iris\iris\__main__.py", line 108, in run_iris                                               
>>     run(master_test_list, tests, browser)                                                              
>>   File "d:\iris\iris\test_runner.py", line 69, in run                                                  
>>     current.run()                                                                                      
>>   File "d:\iris\iris\tests\content_scroll\settings_browser_level.py", line 59, in run                  
>>     assert_true(self, same_value_exists, 'The value is changed to 50')                                 
>>   File "d:\iris\iris\asserts.py", line 78, in assert_true                                              
>>     assert_equal(test_case, actual, True, message)                                                     
>>   File "d:\iris\iris\asserts.py", line 32, in assert_equal                                             
>>     Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))

**Comment by pavelciapa** [comment]
Test is passing in recent test runs and can be closed.
