### ISSUE TITLE
Fix default_search_code_google test

### ISSUE THREAD

**Issue by spronoza** [mozilla/iris_firefox#2861]
Can not reproduce failure described at step: "Client search code is correct for searches from search bar, region US. - [Actual]: https://www.google.com/webhp?client=firefox-b-1-d [Expected]: https://www.google.com/search?client=firefox-b-1-d&q=test" for Linux with the following stacktrace:

>> Traceback (most recent call last):                                                                     
>>   File "/home/user/.local/share/virtualenvs/iris-s-cvVCBB/bin/iris", line 11, in <module>              
>>     load_entry_point('iris', 'console_scripts', 'iris')()                                              
>>   File "/home/user/iris/iris/__main__.py", line 38, in main                                            
>>     run_iris()                                                                                         
>>   File "/home/user/iris/iris/__main__.py", line 108, in run_iris                                       
>>     run(master_test_list, tests, browser)                                                              
>>   File "/home/user/iris/iris/test_runner.py", line 69, in run                                          
>>     current.run()                                                                                      
>>   File "/home/user/iris/iris/tests/search/default_search_code_google.py", line 100, in run             
>>     'Client search code is correct for searches from search bar, region ' + value + '.')               
>>   File "/home/user/iris/iris/asserts.py", line 32, in assert_equal                                     
>>     Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))

**Comment by tracywalker** [comment]
I am unable to reproduce this on my machine here in the US.  However, the search code above in Actual, 'client=firefox-b-1-d' is correct.  We need to determine why the test machine reporting this failure is receiving the somewhat different complete url from Google.  

 As a place to start, please check the language settings on the test machine.

**Comment by yeyartsev** [comment]
Can not reproduce failure described at step: "Client search code is correct for searches from about:newtab page, content search field, region in. - [Actual]: [Expected]: https://www.google.com/search?client=firefox-b-d&q=beats" for Win 7 with the following stacktrace:

>> Traceback (most recent call last):
>> File "C:\Users\dev\.virtualenvs\iris-LqBaZ-qX\Scripts\iris-script.py", line 11, in
>> load_entry_point('iris', 'console_scripts', 'iris')()
>> File "c:\iris\iris\__main__.py", line 38, in main
>> run_iris()
>> File "c:\iris\iris\__main__.py", line 108, in run_iris
>> run(master_test_list, tests, browser)
>> File "c:\iris\iris\test_runner.py", line 69, in run
>> current.run()
>> File "c:\iris\iris\tests\search\default_search_code_google.py", line 159, in run
>> 'field, region ' + value + '.')
>> File "c:\iris\iris\asserts.py", line 32, in assert_equal
>> Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))

**Comment by tracywalker** [comment]
Why did you reduce the timeout lengths and swap paste() with type()? Some machines are slow and require the longer timeouts and paste() is much more reliable than type() when you just need to get a string into a text field. You've made this test less stable on slower machines.

Please return those lines of code to the way they were.

**Comment by tracywalker** [comment]
Why did you reduce the timeout lengths and swap paste() with type()? Some machines are slow and require the longer timeouts and paste() is much more reliable than type() when you just need to get a string into a text field. You've made this test less stable on slower machines.

Please return those lines of code to the way they were.

**Comment by tracywalker** [comment]
I also just got confirmation of why webhp?  appears in our tests.  This happens when a search is run without a query string.  So in our automation, Iris is not always correctly putting the search string in before the search is run.  

I want you to unwind all of the assert_contains that focus just on the client=<code>.  We should be checking the entire url matches as expected. Otherwise we will get intermittent false PASS results.

**Comment by tracywalker** [comment]
I filed https://github.com/mozilla/iris/issues/2991 so we should investigate paste() more closely.
