### ISSUE TITLE
Fix no_crash_closing_pinned test

### ISSUE THREAD

**Issue by yeyartsev** [mozilla/iris_firefox#2865]
Can not reproduce failure described at step: "Third tab is opened - [Actual]: False [Expected]: True" for Linux with the following stacktrace:

>> Traceback (most recent call last):                                                                     
>>   File "/home/user/.local/share/virtualenvs/iris-s-cvVCBB/bin/iris", line 11, in <module>              
>>     load_entry_point('iris', 'console_scripts', 'iris')()                                              
>>   File "/home/user/iris/iris/__main__.py", line 38, in main                                            
>>     run_iris()                                                                                         
>>   File "/home/user/iris/iris/__main__.py", line 108, in run_iris                                       
>>     run(master_test_list, tests, browser)                                                              
>>   File "/home/user/iris/iris/test_runner.py", line 69, in run                                          
>>     current.run()                                                                                      
>>   File "/home/user/iris/iris/tests/antivirus/no_crash_closing_pinned.py", line 45, in run              
>>     assert_true(self, focus_tab_opened, 'Third tab is opened')                                         
>>   File "/home/user/iris/iris/asserts.py", line 78, in assert_true                                      
>>     assert_equal(test_case, actual, True, message)                                                     
>>   File "/home/user/iris/iris/asserts.py", line 32, in assert_equal                                     
>>     Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))

**Comment by tracywalker** [comment]
This test is failing in recent run on Win7.  No recent failures reported on Linux (originally reported against Linux)or Windows and works locally for me on OSX. Please investigate and fix.

I will disable this test case as part of issue #3452
