### ISSUE TITLE
Fix track_protection_turn_off_for_site test

### ISSUE THREAD

**Issue by yeyartsev** [mozilla/iris_firefox#2876]
Can not reproduce failure described at step: "The tracking protection shield is displayed - [Actual]: False [Expected]: True" for Win 7 with the following stacktrace:
----
>> Traceback (most recent call last):                                                                         
>>   File "C:\Users\dev\.virtualenvs\iris-LqBaZ-qX\Scripts\iris-script.py", line 11, in <module>              
>>     load_entry_point('iris', 'console_scripts', 'iris')()                                                  
>>   File "c:\iris\iris\__main__.py", line 38, in main                                                        
>>     run_iris()                                                                                             
>>   File "c:\iris\iris\__main__.py", line 108, in run_iris                                                   
>>     run(master_test_list, tests, browser)                                                                  
>>   File "c:\iris\iris\test_runner.py", line 69, in run                                                      
>>     current.run()                                                                                          
>>   File "c:\iris\iris\tests\private_browsing\track_protection_turn_off_for_site.py", line 42, in run        
>>     assert_true(self, tracking_protection_shield_displayed, 'The tracking protection shield is displayed') 
>>   File "c:\iris\iris\asserts.py", line 78, in assert_true                                                  
>>     assert_equal(test_case, actual, True, message)                                                         
>>   File "c:\iris\iris\asserts.py", line 32, in assert_equal                                                 
>>     Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))

**Comment by pavelciapa** [comment]
Fails on non-retina osx and win10
CNN web page element changed. Check test according to test description

**Comment by pavelciapa** [comment]
click on wrong place for cnn_restore_focus_pattern on retins osx
![image](https://user-images.githubusercontent.com/45387203/62131320-8110a380-b2ca-11e9-912f-51f2ae3c3d2d.png)
