### ISSUE TITLE
Fix keyboard_shortcuts_work_in_search_bar test

### ISSUE THREAD

**Issue by yeyartsev** [mozilla/iris_firefox#2878]
Can not reproduce failure described at step: "Pressing the arrow DOWN key will slide in the search menu. - [Actual]: mozilla [Expected]: mozilla" for Win 7

**Comment by pavelciapa** [comment]
Fails on osx. Suggestions not shown

**Comment by pavelciapa** [comment]
Update test according to new UI

**Comment by spronoza** [comment]
The test failed on the "'Search using Google' is shown as tooltip.". There is no tooltip for the search bar in 71.0b4 build.

**Comment by ranjit-exalt** [comment]
The issue has been already addressed in commit e851acd of PR https://github.com/mozilla/iris_firefox/pull/4234. 

Pull request approved and merged in dev. Closing this issue as no action neede here.
