### ISSUE TITLE
Fix drop_jpeg_image_in_private_window test

### ISSUE THREAD

**Issue by yeyartsev** [mozilla/iris_firefox#2881]
Can not reproduce failure described at step: "JPG test file is available - [Actual]: False [Expected]: True" for Win 7 with the following stacktrace:

>> Traceback (most recent call last):                                                                     
>>   File "C:\Users\dev\.virtualenvs\iris-LqBaZ-qX\Scripts\iris-script.py", line 11, in <module>          
>>     load_entry_point('iris', 'console_scripts', 'iris')()                                              
>>   File "c:\iris\iris\__main__.py", line 38, in main                                                    
>>     run_iris()                                                                                         
>>   File "c:\iris\iris\__main__.py", line 108, in run_iris                                               
>>     run(master_test_list, tests, browser)                                                              
>>   File "c:\iris\iris\test_runner.py", line 69, in run                                                  
>>     current.run()                                                                                      
>>   File "c:\iris\iris\tests\drag_and_drop\drop_jpeg_image_in_private_window.py", line 144, in run       
>>     assert_true(self, test_file_jpg_located, 'JPG test file is available')                             
>>   File "c:\iris\iris\asserts.py", line 78, in assert_true                                              
>>     assert_equal(test_case, actual, True, message)                                                     
>>   File "c:\iris\iris\asserts.py", line 32, in assert_equal                                             
>>     Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))

**Comment by yeyartsev** [comment]
Can not reproduce failure described at step: ""Drop here" pattern is available - [Actual]: False [Expected]: True" for Win 7 with the following stacktrace:
>>   File "C:\Users\dev\.virtualenvs\iris-LqBaZ-qX\Scripts\iris-script.py", line 11, in <module>          
>>     load_entry_point('iris', 'console_scripts', 'iris')()                                              
>>   File "c:\iris\iris\__main__.py", line 38, in main                                                    
>>     run_iris()                                                                                         
>>   File "c:\iris\iris\__main__.py", line 108, in run_iris                                               
>>     run(master_test_list, tests, browser)                                                              
>>   File "c:\iris\iris\test_runner.py", line 69, in run                                                  
>>     current.run()                                                                                      
>>   File "c:\iris\iris\tests\drag_and_drop\drop_jpeg_image_in_private_window.py", line 159, in run       
>>     assert_true(self, drop_here_available, '"Drop here" pattern is available')                         
>>   File "c:\iris\iris\asserts.py", line 78, in assert_true                                              
>>     assert_equal(test_case, actual, True, message)                                                     
>>   File "c:\iris\iris\asserts.py", line 32, in assert_equal                                             
>>     Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))

**Comment by pavelciapa** [comment]
Fix bug in drag and drop tests:

1. - drop_jpeg_image.py
2. - drop_jpeg_image_in_private_window.py
3. - drop_pdf_file.py
4. - drop_pdf_file_in_private_window.py
5. - drop_png_image.py
6. - drop_png_image_in_private_window.py
7. - drop_txt_file.py
8. - drop_txt_file_in_private_window.py
