### ISSUE TITLE
Fix edit_bookmark_from_recently_bookmarked_section test

### ISSUE THREAD

**Issue by nevdokimov** [mozilla/iris_firefox#2890]
Can not reproduce failure described at step: "Properties for "Getting Started" window is opened - [Actual]: False [Expected]: True" for Win 10 with the following stacktrace:
-----------
>> Traceback (most recent call last):                                                                                
>>   File "C:\Users\svuser\.virtualenvs\iris-NcrgrEXF\Scripts\iris-script.py", line 11, in <module>                  
>>     load_entry_point('iris', 'console_scripts', 'iris')()                                                         
>>   File "c:\iriscron2\iris\iris\__main__.py", line 38, in main                                                     
>>     run_iris()                                                                                                    
>>   File "c:\iriscron2\iris\iris\__main__.py", line 108, in run_iris                                                
>>     run(master_test_list, tests, browser)                                                                         
>>   File "c:\iriscron2\iris\iris\test_runner.py", line 69, in run                                                   
>>     current.run()                                                                                                 
>>   File "c:\iriscron2\iris\iris\tests\bookmark\edit_bookmark_from_recently_bookmarked_section.py", line 62, in run 
>>     assert_true(self, properties_window_exists, 'Properties for "Getting Started" window is opened')              
>>   File "c:\iriscron2\iris\iris\asserts.py", line 78, in assert_true                                               
>>     assert_equal(test_case, actual, True, message)                                                                
>>   File "c:\iriscron2\iris\iris\asserts.py", line 32, in assert_equal                                              
>>     Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))

**Comment by pavelciapa** [comment]
Bookmark Properties popup window is loading incorrectly

![photo_2019-04-23_13-35-24](https://user-images.githubusercontent.com/45387203/56574766-bbccb680-65cc-11e9-8a84-cbffb3b09495.jpg)


2019-04-23 01:59:10 [INFO] [iris.test_runner] Executing: 5 - [edit_bookmark_from_recently_bookmarked_section]: Edit a bo
okmark from the Recently Bookmarked section
2019-04-23 01:59:28 [SUCCESS] [iris.test_case] >>> PASSED <<< Step 1: View history, saved bookmarks and more section exi
sts
2019-04-23 01:59:30 [SUCCESS] [iris.test_case] >>> PASSED <<< Step 2: The Bookmarks menu is correctly displayed
2019-04-23 01:59:31 [SUCCESS] [iris.test_case] >>> PASSED <<< Step 3: Getting started bookmark exists
2019-04-23 01:59:33 [SUCCESS] [iris.test_case] >>> PASSED <<< Step 4: Properties option exists
2019-04-23 01:59:35 [SUCCESS] [iris.test_case] >>> PASSED <<< Step 5: Properties for "Getting Started" window is opened
2019-04-23 01:59:40 [WARNING] [iris.test_case] >>> FAILED <<< Step 6: Name field exists - [Actual]: False [Expected]: Tr
ue

-------------------------------------------------------------------------------------------------------------
>> Traceback (most recent call last):                                                                      <<
>>   File "C:\Users\IEUser\.virtualenvs\iris-LqBaZ-qX\Scripts\iris-script.py", line 11, in <module>        <<
>>     load_entry_point('iris', 'console_scripts', 'iris')()                                               <<
>>   File "c:\iris\iris\__main__.py", line 38, in main                                                     <<
>>     run_iris()                                                                                          <<
>>   File "c:\iris\iris\__main__.py", line 108, in run_iris                                                <<
>>     run(master_test_list, tests, browser)                                                               <<
>>   File "c:\iris\iris\test_runner.py", line 69, in run                                                   <<
>>     current.run()                                                                                       <<
>>   File "c:\iris\iris\tests\bookmark\edit_bookmark_from_recently_bookmarked_section.py", line 68, in run <<
>>     assert_true(self, name_before_exists, 'Name field exists')                                          <<
>>   File "c:\iris\iris\asserts.py", line 78, in assert_true                                               <<
>>     assert_equal(test_case, actual, True, message)                                                      <<
>>   File "c:\iris\iris\asserts.py", line 32, in assert_equal                                              <<
>>     Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))  <<
-------------------------------------------------------------------------------------------------------------

**Comment by nevdokimov** [comment]
Can not reproduce failure described at step: "New modified bookmark exists - [Actual]: False [Expected]: True" for OSX

**Comment by tracywalker** [comment]
> Can not reproduce failure described at step: "New modified bookmark exists - [Actual]: False [Expected]: True" for OSX

We know any test that tries to access the bookmarks properties dialog from context menu may intermittently fail due to bug https://bugzilla.mozilla.org/show_bug.cgi?id=1527258.

**Comment by pavelciapa** [comment]
Dialogue box is opened but looks incorrect
![image](https://user-images.githubusercontent.com/45387203/63931423-c4cf0800-ca44-11e9-8266-1ab53438b26a.png)
