### ISSUE TITLE
Fix open_bookmark_new_private_window_from_ibrary test

### ISSUE THREAD

**Issue by nevdokimov** [mozilla/iris_firefox#2891]
Can not reproduce failure described at step: "019-04-17 11:53:58,724 [ERROR] [iris.test_case] >>> ERROR <<< Error encountered in test" for OSX with the following stacktrace:
---------
>> Traceback (most recent call last):                                                                              
>>   File "/Users/admin/iris/iris/test_runner.py", line 69, in run                                                 
>>     current.run()                                                                                               
>>   File "/Users/admin/iris/iris/tests/bookmark/open_bookmark_new_private_window_from_ibrary.py", line 56, in run 
>>     close_window_control('auxiliary')                                                                           
>>   File "/Users/admin/iris/iris/api/helpers/general.py", line 240, in close_window_control                       
>>     find_window_controls(window_type)                                                                           
>>   File "/Users/admin/iris/iris/api/helpers/general.py", line 474, in find_window_controls                       
>>     raise APIHelperError('Can\'t find the auxiliary window controls, aborting.')                                
>> APIHelperError: Can't find the auxiliary window controls, aborting.

**Comment by pavelciapa** [comment]
Test is passing in recent test runs and can be closed.
