### ISSUE TITLE
Fix delete_bookmark_from_recently_bookmarked test

### ISSUE THREAD

**Issue by nevdokimov** [mozilla/iris_firefox#2892]
Can not reproduce failure described at step: "None - [Actual]: None [Expected]: None" for OSX with the following stacktrace:
-----
>> Traceback (most recent call last):                                                                          
>>   File "/Users/admin/iris/iris/test_runner.py", line 69, in run                                             
>>     current.run()                                                                                           
>>   File "/Users/admin/iris/iris/tests/bookmark/delete_bookmark_from_recently_bookmarked.py", line 22, in run 
>>     click(NavBar.LIBRARY_MENU)                                                                              
>>   File "/Users/admin/iris/iris/api/core/mouse.py", line 77, in click                                        
>>     _general_click(where, 1, duration, in_region, 'left')                                                   
>>   File "/Users/admin/iris/iris/api/core/mouse.py", line 298, in _general_click                              
>>     _click_pattern(where, clicks, duration, in_region, button)                                              
>>   File "/Users/admin/iris/iris/api/core/mouse.py", line 273, in _click_pattern                              
>>     raise FindError('Unable to click on: %s' % pattern.get_file_path())                                     
>> FindError: Unable to click on: /Users/admin/iris/iris/api/core/firefox_ui/images/osx/library_button.png

**Comment by pavelciapa** [comment]
Test is passing in recent test runs and can be closed.
