### ISSUE TITLE
Searching with pattern.similar(0.99) or exact() settings throw out error

### ISSUE THREAD

**Issue by alinrus** [mozilla/iris_firefox#2920]
>> Traceback (most recent call last):                                                                                          <<
>>   File "c:\iris\iris\test_runner.py", line 69, in run                                                                       <<
>>     current.run()                                                                                                           <<
>>   File "c:\iris\iris\tests\download_manager\downloads_button_works_properly_positioned_in_the_tabs_bar.py", line 53, in run <<
>>     expected = exists(NavBar.CUSTOM_DOWNLOADS_BUTTON_BLUE.similar(0.99), 30)                                                <<
>>   File "c:\iris\iris\api\core\region.py", line 650, in exists                                                               <<
>>     wait(pattern, timeout, in_region)                                                                                       <<
>>   File "c:\iris\iris\api\core\region.py", line 616, in wait                                                                 <<
>>     image_found = positive_image_search(image_name, timeout, region)                                                        <<
>>   File "c:\iris\iris\api\core\util\image_search.py", line 267, in positive_image_search                                     <<
>>     return _positive_image_search_loop(pattern, timeout, region)                                                            <<
>>   File "c:\iris\iris\api\core\util\image_search.py", line 253, in _positive_image_search_loop                               <<
>>     pos = image_search(pattern, region)                                                                                     <<
>>   File "c:\iris\iris\api\core\util\image_search.py", line 176, in image_search                                              <<
>>     location = _match_template(pattern, stack_image)                                                                        <<
>>   File "c:\iris\iris\api\core\util\image_search.py", line 156, in _match_template                                           <<
>>     position = iris_image_match_template(needle, haystack, precision, None)                                                 <<
>>   File "c:\iris\iris\api\core\util\image_search.py", line 69, in iris_image_match_template                                  <<
>>     min_val, max_val, min_loc, max_loc = cv2.minMaxLoc(res)                                                                 <<
>> TypeError: src is not a numpy array, neither a scalar

**Comment by tracywalker** [comment]
I am amazed that some test development hasn't been blocked by this until now.  It appears no tests have required color pattern matching.

Matt, I'm fairly certain this won't be prioritized for Iris 1. But I think it would be good to get this working correctly in Iris2.

**Comment by tracywalker** [comment]
It seems that 'exact' is similarity of 1.0 per Sikuli. http://doc.sikuli.org/pattern.html?highlight=exact#Pattern.exact
