### ISSUE TITLE
Fix web_console_controls test

### ISSUE THREAD

**Issue by yeyartsev** [mozilla/iris_firefox#2931]
Can not reproduce failure described at step: "Dock to right option works as expected. - [Actual]: False [Expected]: True" for Win 7 with the following stacktrace:

>> Traceback (most recent call last):                                                                     
>>   File "C:\Users\dev\.virtualenvs\iris-LqBaZ-qX\Scripts\iris-script.py", line 11, in <module>          
>>     load_entry_point('iris', 'console_scripts', 'iris')()                                              
>>   File "c:\iris\iris\__main__.py", line 38, in main                                                    
>>     run_iris()                                                                                         
>>   File "c:\iris\iris\__main__.py", line 108, in run_iris                                               
>>     run(master_test_list, tests, browser)                                                              
>>   File "c:\iris\iris\test_runner.py", line 69, in run                                                  
>>     current.run()                                                                                      
>>   File "c:\iris\iris\tests\toolbars_window_controls\web_console_controls.py", line 86, in run          
>>     assert_true(self, dock_to_right_assert, 'Dock to right option works as expected.')                 
>>   File "c:\iris\iris\asserts.py", line 78, in assert_true                                              
>>     assert_equal(test_case, actual, True, message)                                                     
>>   File "c:\iris\iris\asserts.py", line 32, in assert_equal                                             
>>     Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))

**Comment by pavelciapa** [comment]
Seems that region doesn't contain expected element. Need to expand width of region to fix this
 
![Picture](https://user-images.githubusercontent.com/45387203/57131232-75354400-6da4-11e9-817f-1a1db65bc1db.png)

**Comment by pavelciapa** [comment]
- Update pattern

![изображение](https://user-images.githubusercontent.com/45387203/65612002-254d5880-dfa3-11e9-8def-d0869910cadb.png)
