### ISSUE TITLE
Implement API: highlight() (Region method)

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris_firefox#298]

**Comment by silviuFlorin** [comment]
I already have a working solution for Windows using tkinter library. Found this resource for Mac and will give it a try:
https://stackoverflow.com/questions/19080499/transparent-background-in-a-tkinter-window/44296157

**Comment by mwobensmith** [comment]
Whoa, can't wait to see this working! 😁🎉

**Comment by mwobensmith** [comment]
I'm wondering if we really want this as a `Region` API, or if we want it as something we turn on/off for the whole run via a command-line flag.

I think I'd rather do that, by invoking `-h` for `highlight`, which would highlight the items on screen that we are looking for. When we specify a `Region`, we would first highlight the region bounds. When we search for a `Pattern`, highlight that for a brief period of time when we find it. 

That's one way of doing it. What do you think @silviuFlorin ?

**Comment by silviuFlorin** [comment]
@mwobensmith our current implementation  (branch issue_298) is a mix of both your suggestion and the way highlight works in Sikuli. Running a test with -b flag (temporary name - could be changed) will highlight  regions, patterns and mouse clicks. You can always do a region.higlight() anywhere in a test for a more targeted debug

**Comment by mwobensmith** [comment]
This looks good. We can always change the flag name if we think of a better one.

Also, a couple of observations that might be captured in new issues:
* There are situations where we aren't allowed to draw on top of the UI, because it forces itself to the topmost layer, and we draw behind it. We could consider alternate drawing techniques, such as larger rectangles or circles, drawing arrows pointing to the region, animating graphics, etc. to draw attention to the area being examined.
* I noticed that some tests fail when this it turned on. I am guessing that the time required to do the highlight animation affects the wait times of various pattern searches, and therefore, cause failures. We will need to keep an eye on this to be sure, as well as recommend to test authors to be aware of this when using the feature.
