### ISSUE TITLE
Test case: Bug 1403951 - [Win10] Browser window doesn't display when Dark/Light theme is enabled on Windows 10.

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris_firefox#3004]
https://testrail.stage.mozaws.net/index.php?/cases/view/118731

note: test case feature ID is 1998 and this test belongs in iris/tests/toolbars_window_controls

**Comment by ranjit-exalt** [comment]
@tracywalker: This test case has been removed from the test rail. Please check and let me know if it has been moved to some other place.

**Comment by tracywalker** [comment]
> @tracywalker: This test case has been removed from the test rail. Please check and let me know if it has been moved to some other place.

The test ID was a typo.  I have updated with the correct ID.

**Comment by ranjit-exalt** [comment]
Closing as Issue merged.
