### ISSUE TITLE
Test case: When the site that you're trying to visit is not an deceptive site, you can ignore the warning.

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris_firefox#3046]
https://testrail.stage.mozaws.net/index.php?/cases/view/50354

**Comment by spronoza** [comment]
@tracywalker Question about the second step in the TestRail. Do we really need to wait a 5 minutes for V4 protocol and 14 hours for V2 protocol? And how do we recognize which protocol is used? 
Same question for #3047

**Comment by tracywalker** [comment]
I missed the extensive wait required in the test. this test case is unsuitable for Iris, we're not going to wait for 14 hours.

**Comment by tracywalker** [comment]
I missed the extensive wait required in the test. this test case is unsuitable for Iris, we're not going to wait for 14 hours.
