### ISSUE TITLE
Test case: When the site that you're trying to visit is not an attack site, you can ignore the warning.

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris_firefox#3047]
https://testrail.stage.mozaws.net/index.php?/cases/view/50355

**Comment by tracywalker** [comment]
I missed the extensive wait required in the test. this test case is unsuitable for Iris, we're not going to wait for 14 hours.

**Comment by spronoza** [comment]
> I missed the extensive wait required in the test. this test case is unsuitable for Iris, we're not going to wait for 14 hours.

Ok, tnx
