### ISSUE TITLE
Test case: Close Firefox browser when updating safe browsing DB.

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris_firefox#3049]
https://testrail.stage.mozaws.net/index.php?/cases/view/50359

**Comment by spronoza** [comment]
@tracywalker It is not possible to close Firefox browser when the status is "updating" because it updating too fast even with throttling. Should we skip checking “updating” status and restart browser or not automate that test case at all?

**Comment by tracywalker** [comment]
@spronoza:  I don't how this was run manually fast enough. Anyway yes, develop the test case by immediately restarting the browser after initiating the DB update. The best we can do is verify the DB is up to date after browser restart.

**Comment by spronoza** [comment]
> @spronoza: I don't how this was run manually fast enough. Anyway yes, develop the test case by immediately restarting the browser after initiating the DB update. The best we can do is verify the DB is up to date after browser restart.

Ok, thank
