### ISSUE TITLE
Fix user_is_prompted_when_trying_to_close_the_browser_while_downloading test

### ISSUE THREAD

**Issue by yeyartsev** [mozilla/iris_firefox#3059]
Can not reproduce failure described after step 3: 
"Error encountered in test" for Win 7 with the following stacktrace:
>>   File "c:\iris\iris\test_runner.py", line 69, in run                                                                                
>>     current.run()                                                                                                                    
>>   File "c:\iris\iris\tests\download_manager\user_is_prompted_when_trying_to_close_the_browser_while_downloading.py", line 52, in run 
>>     download_file(pattern, DownloadFiles.OK)                                                                                         
>>   File "c:\iris\iris\api\helpers\download_manager_utils.py", line 173, in download_file                                              
>>     raise APIHelperError('The \'Save file\' option is not present in the page, aborting.')                                           
>> APIHelperError: The 'Save file' option is not present in the page, aborting.

**Comment by yeyartsev** [comment]
Can not reproduce failure after step 3 described as:
 "Error encountered in test" for Win 7 with the following stacktrace:
>>   File "c:\iris\iris\test_runner.py", line 69, in run                                                                                
>>     current.run()                                                                                                                    
>>   File "c:\iris\iris\tests\download_manager\user_is_prompted_when_trying_to_close_the_browser_while_downloading.py", line 52, in run 
>>     download_file(pattern, DownloadFiles.OK)                                                                                         
>>   File "c:\iris\iris\api\helpers\download_manager_utils.py", line 173, in download_file                                              
>>     raise APIHelperError('The \'Save file\' option is not present in the page, aborting.')                                           
>> APIHelperError: The 'Save file' option is not present in the page, aborting.

**Comment by yeyartsev** [comment]
Test fails against win7 after step 3 described as:
"Error encountered in test" for Win 7 with the following stacktrace:

        File "c:\iris\iris\test_runner.py", line 69, in run
        current.run()
        File "c:\iris\iris\tests\download_manager\user_is_prompted_when_trying_to_close_the_browser_while_downloading.py", line 52, in run
        download_file(pattern, DownloadFiles.OK)
        File "c:\iris\iris\api\helpers\download_manager_utils.py", line 173, in download_file
        raise APIHelperError('The 'Save file' option is not present in the page, aborting.')
        APIHelperError: The 'Save file' option is not present in the page, aborting.

**Comment by pavelciapa** [comment]
Test is passing in recent test runs and can be closed.
