### ISSUE TITLE
Fix show_all_downloads_states test

### ISSUE THREAD

**Issue by yeyartsev** [mozilla/iris_firefox#3060]
The test fails after step 11: "None - [Actual]: None [Expected]: None" for Win 7 with the following stacktrace:
>>   File "c:\iris\iris\test_runner.py", line 69, in run                                                                   
>>     current.run()                                                                                                       
>>   File "c:\iris\iris\tests\download_manager\show_all_downloads_states.py", line 71, in run                              
>>     for step in cancel_in_progress_downloads_from_the_library():                                                        
>>   File "c:\iris\iris\api\helpers\download_manager_utils.py", line 109, in cancel_in_progress_downloads_from_the_library 
>>     raise FindError('Could not get the x-coordinate of the library window title.')                                      
>> FindError: Could not get the x-coordinate of the library window title.

**Comment by pavelciapa** [comment]
Test is passing in recent test runs and can be closed.
