### ISSUE TITLE
Test case: Bug 1363960 - New "Preferences" page on 1024x768 screens extends horizontally off-screen (with horizontal scroll bar) doesn't look very good, and not very easy to use.

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris_firefox#3067]
https://testrail.stage.mozaws.net/index.php?/cases/view/145230

**Comment by pavelciapa** [comment]
Test completed, without following precondition:

> Preconditions
> Have screen resolution of 1024 x 768.
>
