### ISSUE TITLE
Test case: Bug 1129597 - Unable to edit keyword.

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris_firefox#3071]
https://testrail.stage.mozaws.net/index.php?/cases/view/145302

**Comment by pavelciapa** [comment]
> 4 Type keyword and do not press ENTER key now (e.g. "b" not include quotation).
> 	An input field appears and the keyword is written.
> 
> 5 Click "General" pane then click "Search" pane.
> 	The about:preferences#search is successfully loaded.
> 
> 6 Attempt to continue to type keyword (e.g. "ing" following "b").
> 	The word can be typed.

When on Step 6 I get back to "Search" I got into begining of a page, with Keyword field non active, and window scrolled to top (I have to scroll to see first Keyword field)
https://testrail.stage.mozaws.net/index.php?/cases/view/145302

**Comment by tracywalker** [comment]
Can the issue with what you reported after step 6 be reproduced by hand?  If so, it sounds like a bug in Firefox.

**Comment by tracywalker** [comment]
Ranjit, the TetsRail test case has been updated to reflect having to double click the keyword again.  You can proceed with Iris test case using the updated steps.

**Comment by ranjit-exalt** [comment]
Code Merged. Closing Issue.
