### ISSUE TITLE
Test case: Firefox can be set to always use private browsing mode.

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris_firefox#3080]
https://testrail.stage.mozaws.net/index.php?/cases/view/143606

**Comment by yeyartsev** [comment]
@tracywalker There is a question about the last test step. During the test, we are going to download a file, but there is no download mentioned in check. The recently downloaded file remains in library/downloads. 
Should we check downloaded file in "downloads" section?

**Comment by tracywalker** [comment]
Yes, any time a test requires downloading a file, use the files we set up locally for the download manager tests.

**Comment by tracywalker** [comment]
Downloading a file is not a private action. As such. yes, the downloaded file should show up in  the downloads folder. The testrail test expectations aren't detailed enough for the last step.  Please develop the test for the actual expectations of downloads from private window.  Thanks @yeyartsev.
