### ISSUE TITLE
Test case: Search bar can be successfully added/removed from the toolbar.

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris_firefox#3104]
https://testrail.stage.mozaws.net/index.php?/cases/view/143589

**Comment by pavelciapa** [comment]
> Search bar can be successfully added/removed from the toolbar

@tracywalker: test description doesn't correspond to its steps; we only add search bar and perform check

**Comment by tracywalker** [comment]
Pavel, I updated the TestRail test case steps to remove the search bar as the test case description indicates.
