### ISSUE TITLE
Test case: Firefox can be set to display the home page on launch.

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris_firefox#3111]
https://testrail.stage.mozaws.net/index.php?/cases/view/143543

**Comment by pavelciapa** [comment]
Check Home Page with pattern `Utils.TOP_SITES` , which indicates certain content of Home Page. Instead of `Tabs.NEW_TAB_HIGHLIGHTED`
![image](https://user-images.githubusercontent.com/45387203/57516951-71fb0480-731e-11e9-888a-cb45701cb67f.png)

**Comment by yeyartsev** [comment]
@tracywalker There is a problem with completing this issue using iris2. In iris2 Firefox must be restarted using `firefox.restart()` call. Unfortunately, webpage opened after this call is either default iris page or with page by url, given as `url` argument. This situation conflicts with last step test requirements.

**Comment by yeyartsev** [comment]
@tracywalker There is a possible workaround - open new window after firefox restart.

**Comment by tracywalker** [comment]
The suggested workaround doesn't correctly replicate the test to load home page directly on browser launch.  We may have to mark this one unsuitable for Iris, if we can't find a correct workaround.

**Comment by pavelciapa** [comment]
Or we can fix `firefox.restart() `to work as in Iris1.0

**Comment by tracywalker** [comment]
This needs issue #3207
