### ISSUE TITLE
Test case: Firefox can be set as default browser via about:preferences#general page.

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris_firefox#3126]
https://testrail.stage.mozaws.net/index.php?/cases/view/143542

**Comment by pavelciapa** [comment]
When changing default browser, there are few Firefoxes, one is for Iris.
When launch Firefox not from Iris, there is one Firefox

Disabled for Windows10 

![image](https://user-images.githubusercontent.com/45387203/59673203-623dce00-91b0-11e9-83f9-a8478c224399.png)

**Comment by tracywalker** [comment]
Pavel, write the test to select the first Firefox in the list.  Then see if that sets the default browser to the one the test needs.  If not, then rewrite the test to select the second Firefox in the list.  If neither one works correctly consistently, we'll have to skip this test for Windows.

**Comment by pavelciapa** [comment]
Also need to be sure that Firefox is not default browser before test

**Comment by pavelciapa** [comment]
> 
> 
> Pavel, write the test to select the first Firefox in the list. Then see if that sets the default browser to the one the test needs. If not, then rewrite the test to select the second Firefox in the list. If neither one works correctly consistently, we'll have to skip this test for Windows.

I have even more Firefoxes. And number varies on different Win10 machines.
![image](https://user-images.githubusercontent.com/45387203/59764686-cd100780-928b-11e9-929e-70e942834b84.png)

**Comment by pavelciapa** [comment]
Also, we need to have other then Firefox default browser to pass this test. And after test, we should bring settings back.

**Comment by tracywalker** [comment]
> Also, we need to have other than Firefox default browser to pass this test. And after test, we should bring settings back.

Isn't the version of Firefox downloaded for Iris always not default browser?  And yes,  it would be best practice to return the default to another browser;  problem being which one.

I am becoming more and more inclined to mark this one unsuitable for Iris.

**Comment by pavelciapa** [comment]
> Isn't the version of Firefox downloaded for Iris always not default browser?

For example, for OSx second run of test says that Firefox is already a default browser. 

> to return the default to another browser; problem being which one.

For example return default to Safari means to open Safari browser, or system preferences; which is not very common Iris usages

**Comment by pavelciapa** [comment]
> I am becoming more and more inclined to mark this one unsuitable for Iris.

closing and unsuitable for Iris
