### ISSUE TITLE
Fix number_of_downloads_properly_truncated test

### ISSUE THREAD

**Issue by yeyartsev** [mozilla/iris_firefox#3154]
The test fails after step 2:
 "Error encountered in test" for Win 7 with the following stacktrace:
>>   File "c:\iris\iris\test_runner.py", line 69, in run                                                   
>>     current.run()                                                                                       
>>   File "c:\iris\iris\tests\download_manager\number_of_downloads_properly_truncated.py", line 55, in run 
>>     download_file(f, DownloadFiles.OK)                                                                  
>>   File "c:\iris\iris\api\helpers\download_manager_utils.py", line 173, in download_file                 
>>     raise APIHelperError('The \'Save file\' option is not present in the page, aborting.')              
>> APIHelperError: The 'Save file' option is not present in the page, aborting.

**Comment by yeyartsev** [comment]
Second step failure is still reproducible against win7

**Comment by pavelciapa** [comment]
Test is passing in recent test runs and can be closed.
