### ISSUE TITLE
Fix enable_bookmarks_sidebar_from_bookmarks_menu test

### ISSUE THREAD

**Issue by yeyartsev** [mozilla/iris_firefox#3158]
Can not reproduce failure described at step: "Error encountered in test" for Win 7 with the following stacktrace:
>>   File "c:\iris\iris\test_runner.py", line 69, in run                                                                                                          
>>     current.run()                                                                                                                                              
>>   File "c:\iris\iris\tests\bookmark\enable_bookmarks_sidebar_from_bookmarks_menu.py", line 23, in run                                                          
>>     access_bookmarking_tools(view_bookmarks_sidebar_pattern)                                                                                                   
>>   File "c:\iris\iris\api\helpers\general.py", line 46, in access_bookmarking_tools                                                                             
>>     raise APIHelperError('Can\'t find the %s option, aborting.' % option)                                                                                      
>> APIHelperError: Can't find the (view_bookmarks_sidebar.png, c:\iris\iris\api\core\firefox_ui\images\win7\view_bookmarks_sidebar.png, 1, 0.8) option, aborting.

**Comment by pavelciapa** [comment]
Test is passing in recent test runs and can be closed.
