### ISSUE TITLE
Fix remove_tag_from_bookmark_via_stardialog test

### ISSUE THREAD

**Issue by yeyartsev** [mozilla/iris_firefox#3160]
Can not reproduce failure described at step: "The Iris tag exists - [Actual]: False [Expected]: True" for Win 7 with the following stacktrace:
>>   File "C:\Users\dev\.virtualenvs\iris-LqBaZ-qX\Scripts\iris-script.py", line 11, in <module>          
>>     load_entry_point('iris', 'console_scripts', 'iris')()                                              
>>   File "c:\iris\iris\__main__.py", line 38, in main                                                    
>>     run_iris()                                                                                         
>>   File "c:\iris\iris\__main__.py", line 108, in run_iris                                               
>>     run(master_test_list, tests, browser)                                                              
>>   File "c:\iris\iris\test_runner.py", line 69, in run                                                  
>>     current.run()                                                                                      
>>   File "c:\iris\iris\tests\bookmark\remove_tag_from_bookmark_via_stardialog.py", line 68, in run       
>>     assert_true(self, iris_tag_exists, 'The Iris tag exists')                                          
>>   File "c:\iris\iris\asserts.py", line 78, in assert_true                                              
>>     assert_equal(test_case, actual, True, message)                                                     
>>   File "c:\iris\iris\asserts.py", line 32, in assert_equal                                             
>>     Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))

**Comment by pavelciapa** [comment]
Test is passing in recent test runs and can be closed.

**Comment by dbakaev** [comment]
Fails on win7
