### ISSUE TITLE
Failed to install tesseract with bootstrap.sh

### ISSUE THREAD

**Issue by MarisBogdan** [mozilla/iris_firefox#3190]
Trying to do a fresh install of iris on an Ubuntu 16.04 machine and when running ./bootstrap/bootstrap.sh I get this output in the terminal:

`  --->  installing/upgrading Leptonica #####

./bootstrap/linux_bootstrap.sh: line 93: tesseract: command not found

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
\n\033[0;31m  --->  leptonica-1.76.0 directory not found! Maybe the extraction failed. \033[0m\n
svuser@laptop385:~/iris$ `

**Comment by mwobensmith** [comment]
@MarisBogdan have you tried to run this more than once? I am curious to see if the problem corrects itself.

**Comment by MarisBogdan** [comment]
I did run it multiple times, updated ubuntu (apt-get update), restarted, ran the command again and I got the same error. 
Anthony, who was in the same office as me, got the same error.

**Comment by ashughes1** [comment]
I just tried it again and the same error is occurring.

**Comment by ashughes1** [comment]
So I found out that where this is failing is trying to unzip the leptonica-1.76.0.tar.gz which the script downloads to /root/. If I sudo su to the /root/ folder, delete the leptonica gz file and redownload it I can unzip it manually then continue with bootstrap. But if the process runs by itself through the script it fails.

I have no idea why if the file is downloaded via bootstrap it thinks it's an invalid gzip file but if it's downloaded manually the file is valid.

Of course now that it's been download and built once successfully I can no longer reproduce this. Is there a way to purge all the dependencies and start from scratch?

**Comment by ashughes1** [comment]
Got further but now I get this:

 >  --->  Downloading and installing Tesseract data #####
 >  --->  Tessdata archive 4.0.0.zip is not the correct size. Maybe download was stopped or did not completely finish. 
 >       Please delete the file and restart the process.

**Comment by ashughes1** [comment]
Deleted everything in /root and tried running bootstrap again worked around the above.

**Comment by ashughes1** [comment]
@MarisBogdan is this still an issue on your Ubuntu 16.04 machine?

**Comment by MarisBogdan** [comment]
Yep, just got my hands on a 16.04 machine and the same error appears when running bootstrap.sh

  --->  installing/upgrading Leptonica #####

./bootstrap/linux_bootstrap.sh: line 93: tesseract: command not found
\n\033[0;32m  --->  Downloading leptonica-1.76.0.tar.gz \033[0m\n
--2019-05-22 17:31:59--  http://www.leptonica.com/source/leptonica-1.76.0.tar.gz
Resolving www.leptonica.com (www.leptonica.com)... 172.217.18.83, 2a00:1450:400d:809::2013
Connecting to www.leptonica.com (www.leptonica.com)|172.217.18.83|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://www.leptonica.org [following]
--2019-05-22 17:31:59--  http://www.leptonica.org/
Resolving www.leptonica.org (www.leptonica.org)... 208.67.207.65
Connecting to www.leptonica.org (www.leptonica.org)|208.67.207.65|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7145 (7,0K) [text/html]
Saving to: ‘leptonica-1.76.0.tar.gz’

leptonica-1.76.0.ta 100%[===================>]   6,98K  41,9KB/s    in 0,2s    

2019-05-22 17:32:00 (41,9 KB/s) - ‘leptonica-1.76.0.tar.gz’ saved [7145/7145]


gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
\n\033[0;31m  --->  leptonica-1.76.0 directory not found! Maybe the extraction failed. \033[0m\n

**Comment by ashughes1** [comment]
@MarisBogdan 

> leptonica-1.76.0.ta 100%[===================>] 6,98K 41,9KB/s in 0,2s

Looks like its downloading a .ta file instead of a .tar.gz file. Can you check the /root folder to see if the file it downloaded is valid?

As well, it my be a good idea to checksum the file downloaded by bootstrap versus the file downloaded manually from the website. See if these two files get the same value.

**Comment by rrobotin** [comment]
@MarisBogdan @ashughes1  Seems that leptonica moved to from 'com' to 'org' domain so when the leptonica archive file is downloaded from the old domaine(using 'wget') is corupted. Even if the redirect to the new domain is done correctly. I've updated the linux_bootstrap to use the new leptonica archive link (PR #3202 )

**Comment by ashughes1** [comment]
This was wiped out in the migration to Iris 2. Reopening to fix it again.
