### ISSUE TITLE
Fix history_menu_open_site_in_private_window test case 

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris_firefox#3211]
copied from iris2

`history_menu_open_site_in_private_window ` test case is failing due to an malfunction of the open_library_menu(option) function. The region must be reduced in order to eliminate the noise for the ocr. This issue is reproducible on Windows platforms.

**Comment by pavelciapa** [comment]
Same issue covered in #2897

**Comment by pavelciapa** [comment]
Test failed on last image where page loaded - `Mozilla page loaded successfully.`

![image](https://user-images.githubusercontent.com/45387203/63783997-73583900-c8dd-11e9-9a67-e91622be7513.png)
