### ISSUE TITLE
Some download tests are leaving Firefox instances behind

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris_firefox#3234]
There is a likely runtime error in some of the download tests that causes iris to leave Firefox instances open.

**Comment by tracywalker** [comment]
Does it seem to be consistent which tests are doing this?  If so, which ones?

In any case, we should make the Firefox quit method more robust

**Comment by pavelciapa** [comment]
download_manager leaves opened 5-10 windowses after suite run on Linux

- investigate and fix

**Comment by mwobensmith** [comment]
@tracywalker I think this is fixed now.

**Comment by tracywalker** [comment]
Yes, I think this has been fixed in various other issues.
