### ISSUE TITLE
Fix for disable_web_search_awesomebar

### ISSUE THREAD

**Issue by spronoza** [mozilla/iris_firefox#3241]
Fix for disable_web_search_awesomebar.py

**Comment by spronoza** [comment]
> 

  | Step | Expected Result
-- | -- | --
3 | Go to about:config and set the preference keyword.enabled to false. | The pref code keyword.enabled has the value false.
4 | Enter a search in the URL bar and hit enter. | The search is executed with URL autocomplete.

@tracywalker There is no autocomplete in URL bar. Does that test case still actual?

**Comment by tracywalker** [comment]
Those steps work for me when I manually follow them.
