### ISSUE TITLE
Open Firefox instances to default size to avoid clipping

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris_firefox#3248]
I have noticed that the Firefox instance can open just a little too large on my Linux laptop, causing the Iris logo to be clipped off-screen, and therefore causing the test not to load.

If we open the browser to a slightly smaller region, we can guarantee the display of this image, and the browser validation logic will pass.

**Comment by pavelciapa** [comment]
I faced similar issue, when Linux see that some window is opened on the left corner, and places new Firefox window slightly aside to the right, and part of Iris logo is covered, and test fails.

**Comment by mwobensmith** [comment]
I am still debugging this now. I can see that the Linux windowing system also affects the placement of the Firefox browser window when it opens. If there is an open operating system window, Firefox opens to the right, as you have noticed. 

I am looking for a way to guarantee the correct placement of the Firefox window via Fx command line options, as well as the xulstore.json inside the profile. However, I don't want to break existing tests either, so I'm still experimenting with this.

**Comment by mwobensmith** [comment]
Simplest thing to do is pass `-height 600 -width -800` to the Firefox instance to control the window size. We will have to instruct Linux users to close all active OS windows to prevent Firefox from being positioned too far to the right/bottom.

**Comment by pavelciapa** [comment]
We have faced this issue on Linux for tests:
```
position_window_restored.py
scroll_each_window.py
```
we have had few windows there, and used regions to find correct window location

**Comment by tracywalker** [comment]
Is there some sort of system controlled window position making the windows 'tile' down and right for each new window opened?

**Comment by mwobensmith** [comment]
I will back out my fix. The solution for now is to close all active windows on Linux before you trigger a run, to avoid Ubuntu's window tiling behavior.

**Comment by mwobensmith** [comment]
Ideally we should figure out what controls the window tiling behavior on Ubuntu. 

In the meantime, we should update our setup docs to ask Ubuntu users to run Iris without any open windows if they want predictable window location. This is a bit outside what Iris can control.
