### ISSUE TITLE
navigate() fails when goes after "def run(self, firefox):"

### ISSUE THREAD

**Issue by pavelciapa** [mozilla/iris_firefox#3259]
```
    def run(self, firefox):
        navigate('about:preferences')
```
![image](https://user-images.githubusercontent.com/45387203/59434757-b412dc80-8ddb-11e9-87e0-e3ec44a97812.png)

Solution is to add waiter to navigate method, or after finding Iris logo

**Comment by tracywalker** [comment]
I think this is just something to avoid in test case creation.
