### ISSUE TITLE
Antivirus test set updates .2

### ISSUE THREAD

**Issue by cfogelSV** [mozilla/iris_firefox#3272]
Further updates for the following tests:

Marked as completed:
https://testrail.stage.mozaws.net/index.php?/cases/view/217852
- at step 6, we've changed the wait time from 1 minute to an interval of 1-5 minutes since sometimes it takes a while to start;

Marked as suitable:
https://testrail.stage.mozaws.net/index.php?/cases/view/225144
- swapped previous steps 3-4;
- added instructions for current step 3 on how to install the certificate from the Firefox browser.

**Comment by tracywalker** [comment]
The first would essentially be covered by our update tests, if you run those test on a machine with anti-virus enabled.

The second has been completed.
