### ISSUE TITLE
Add function that returns if pattern exists in region taken from given pattern

### ISSUE THREAD

**Issue by pavelciapa** [mozilla/iris_firefox#3348]
Add method which receives a pattern with option and checkbox, and return true/false whether checkbox in pattern is checked or not

Iris has problem when distinguish checked option and unchecked options. 
It processes both checked/unchecked patterns as they are same.

**Comment by tracywalker** [comment]
Which check boxes does this pertain to?  There are many styles of check boxes.  If you write a method for returning checked or not,  it will only apply to one style of checkbox.

Anyway, the issue for test cases is in pattern similarity.  You may have to use exact() (or .similarity(0.99)) combined with tighter region use to find checked vs unchecked.

**Comment by pavelciapa** [comment]
> Which check boxes does this pertain to?

this pertain to checkboxes in about:preferences, for now.
we want method to search checked/unchecked box pattern in given pattern which contains option and checkbox. It also can check different system element present in given option pattern

**Comment by pavelciapa** [comment]
We came to solution that will be handy and universal – to check if inner pattern is found in bigger outer pattern
