### ISSUE TITLE
Fix Travis script

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris_firefox#3349]
This has already been fixed on the core repo, but the `iris_firefox` project needs a different smoke test, since it involves Firefox tests.

**Comment by tracywalker** [comment]
I think I may have accidentally reverted this when resolving conflicts during the core Iris merge.

**Comment by mwobensmith** [comment]
No worries, next time you get core code, you'll get a new travis file that will fix this. 

We will still need to customize it for `iris_firefox` to run the smoke tests for Firefox.
