### ISSUE TITLE
Fix settings_gear_is_displayed_and_can_be accessed.py

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris_firefox#3428]
The Firefox bug blocking this has been fixed.  However, this test is failing for me attempting to right click on the settings gear.  The mouse moves to the gear, but the dialog that should be opened from the right click does not appear.

**Comment by pavelciapa** [comment]
For me it doesn't open either.
in test case it says: 
https://testrail.stage.mozaws.net/index.php?/cases/view/108260
- Right Click on settings gear.
- **If a context menu is opened** it should not contain the options Search in new tab and Set as default search engine.

maybe keyword here is **May be**, and test creator knew that it don't work everytime

**Comment by pavelciapa** [comment]
Also, `lines 43-48` are excess

**Comment by pavelciapa** [comment]
> keyword here is **If**, and test creator knew that it won't work everytime

Waiting for answer from test creator

**Comment by pavelciapa** [comment]
> No, It depends on what build are you running the tests.
> 
> esr 60.8 displays the menu
> 
> and for nightly and beta the menu is no longer available

@tracywalker what should we do here?

**Comment by tracywalker** [comment]
esr60 is no longer relevant because esr has been bumped to version 68.  The test case in testrail should no longer contain the **If a context menu is opened ** check for context menu.

Please develop this test by ignoring the check for the context menu.

**Comment by pavelciapa** [comment]
Right click on a gear is not creating a context menu. 
@tracywalker is this a bug or new behavior?

**Comment by tracywalker** [comment]
Right click on the settings gear in this test is no longer a function in Firefox.  As said before, please ignore that part of the test.  The STR's in the test rail test are outdated.

**Comment by pavelciapa** [comment]
Ok, I will ignore it, and message a test creator about outdated STR
