### ISSUE TITLE
Formatting in email_client.py

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [mozilla/iris_firefox#3437]
src/email_report/email_client.py -> Needs some formatting particularly where lots of \n and + are mixed

**Comment by mwobensmith** [comment]
This is core code. It should be fixed there instead. I've opened an issue there - please feel free to fix and submit a PR there. Thank you!

https://github.com/mozilla/iris/issues/537

**Comment by Abdur-rahmaanJ** [comment]
@mwobensmith done
