### ISSUE TITLE
Fix data_after_shutdown test

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris_firefox#3455]
Despite recent efforts, this is still failing in recent runs on Linux and Windows.  It worked for me on OSX. Please investigate and fix.

I will disable this test as part of issue #3452

**Comment by pavelciapa** [comment]
Bug filed on Bugzilla

https://bugzilla.mozilla.org/show_bug.cgi?id=1569146

**Comment by spronoza** [comment]
Replace external web sites with local web
