### ISSUE TITLE
Fix unsafe_websites_warnings test

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris_firefox#3460]
This failed on a recent test run for Window10.  It doesn't appear to be failing on other platforms.  Please investigate and fix.

**Comment by pavelciapa** [comment]
I confirm it fails on win10,win7
after click on update appears **error**, but should _**success**_ as near google4

![2019_08_06_11_49_30_797648_found](https://user-images.githubusercontent.com/45387203/62525875-b156c580-b827-11e9-90dd-d287a0d69bca.jpg)

@tracywalker, is this a bug?

**Comment by pavelciapa** [comment]
**NS_ERROR_FILE_IS_LOCKED (0x8052000E)**
    This error indicates that a file cannot be accessed because it is locked, typically because the file is already being used by another application.

**Comment by tracywalker** [comment]
Can you reproduce the problem outside of Iris, on Firefox, following the test instructions?  https://testrail.stage.mozaws.net/index.php?/cases/view/219580

**Comment by spronoza** [comment]
@tracywalker It is not reproducible outside of Iris. Should we block this test for Win platforms?

**Comment by tracywalker** [comment]
@spronoza, yes, please block_by using this issue for Windows while we continue to investigate.

**Comment by tracywalker** [comment]
Leaving open for investigation into Windows failure.

**Comment by tracywalker** [comment]
this test is now getting error of ''_Settings' object has no attribute 'FIREFOX_TIMEOUT''

Simple fix to use correct version of the timeout.

**Comment by tracywalker** [comment]
I also fixed the issue on Windows and re-enabled the test.
