### ISSUE TITLE
Make info pop-ups not showing by default

### ISSUE THREAD

**Issue by spronoza** [mozilla/iris_firefox#3468]
Info pop-ups like New in Firefox shouldn't be shown by default

**Comment by tracywalker** [comment]
Some of these popups are handled by mozrunner or something.  We should add bits to the  https://github.com/mozilla/iris_firefox/blob/master/src/base/testcase.py in `setup()` for the Content Blocking dialog that often pops up.  Something like
`self.set_profile_pref({'browser.contentblocking.introCount': 20})`

and another line for the add-ons in Private browsing dialog. We'll have to investigate which pref(s) control it.

**Comment by tracywalker** [comment]
https://github.com/mozilla/iris_old/blob/master/iris/test_case.py  from Iris 1 shows what things used to look like.  Much of what is in there, for Iris1 has been pulled out to core. And much of what is in setup() is no necessary because of being handled by moz* api's

**Comment by paulprokhorovmoz** [comment]
I think we just need to add the `'browser.contentblocking.introCount': 20` value into the `DEFAULT_FX_PREFS` variable of the `_Settings` class, so I'm going to change preferences of our default profile.

**Comment by tracywalker** [comment]
Just recapping what we discussed in Slack.  If this is the correct method to adjust prefs at run time, and they can be overridden by a test case, if need be,  Then Paul's solution is fine.

We still need to determine what the prefs are for the addons in private window dialog.

**Comment by tracywalker** [comment]
The addons in private window dialog will be blocked default in all profiles besides BRAND_NEW
