### ISSUE TITLE
Figure out how to make tests get the correct default search engine 

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris_firefox#3509]
Matt thinks we can adjust, the prefs.js file with a value for browser.search.region, on the fly, before the test is executed.  I have tried this with adding preferences={‘browser.search.region’: ‘RU’} to pytest.mark.details.  It doesn't work, the region remains US.

The tests involved are:
default_search_engine_google.py (browser.search.region = US)
default_search_engine_yandex.py (browser.search.region = RU)
default_search_engine_baidu.py (browser.search.region = CN)

I suggest that we create three profiles each based on the search engine required by using inserting the base region for each search engine in the prefs.js file prior to the build ever being launched.  Then add these profiles to Iris so that we have the default search engine set correctly for tests that need it.

**Comment by mwobensmith** [comment]
How else would you change the region? It looks like we are already doing the right thing with `prefs.js`. Is Firefox just being smart and sensing that you are in the US region, and not allowing you to override it?

**Comment by tracywalker** [comment]
Currently there are bugs in Firefox that are messing with the search engines.  We should probably just disable these tests until Firefox sorts out the problems.

**Comment by tracywalker** [comment]
I will block the tests now with block_by this issue.  There are multiple bugs on file we can keep an eye on.  https://bugzilla.mozilla.org/show_bug.cgi?id=1566600, https://bugzilla.mozilla.org/show_bug.cgi?id=1565836 and https://bugzilla.mozilla.org/show_bug.cgi?id=1556789.

**Comment by tracywalker** [comment]
We have sorted this out.  Test fixes are landing as part of issue #3462
