### ISSUE TITLE
Fix migration issue for outdated usage of modifier=KeyModifier.CMD + KeyModifier.SHIFT

### ISSUE THREAD

**Issue by pavelciapa** [mozilla/iris_firefox#3517]
Replace wrongly migrated `modifier=KeyModifier.CMD + KeyModifier.SHIFT` with `modifier=[KeyModifier.CMD, KeyModifier.SHIFT]` in two occurrences

**Comment by tracywalker** [comment]
I see this syntax error in two files (other than the drag/drop cases fixed in https://github.com/mozilla/iris_firefox/issues/3516):  bookmark_import_from_html.py and file picker_utils.py

**Comment by pavelciapa** [comment]
> I see this syntax error in two files (other than the drag/drop cases fixed in #3516): bookmark_import_from_html.py and file_picker_utils.py

Yes, we just made separate PR for drag/drop suite
