### ISSUE TITLE
FIx disable_one_off_searches_from_awesomebar test on OSX

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris_firefox#3523]
This test works for me on my non-retina Mac.  However,  nightly test run reports are consistently reported as failing on non-retina Mac and Windows.

Please investigate and fix.

**Comment by pavelciapa** [comment]
Fails due to captcha

**Comment by tracywalker** [comment]
The captcha from search providers is something we will have to look out for once we put Iris into production on remote machines, that are in a location independent of our test development.  For now, there is nothing we can do about it, other than wait to see if running/developing these tests in certain IP locations less will eventually make the problem go away.  We can either live with the test failure noise or disable all affected tests until the noise dies down.
