### ISSUE TITLE
Fix disable_search_suggestions test

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris_firefox#3524]
This test is failing the pattern match assert for show_search_suggestions_in_address_bar_results_checked_pattern.png
The test will probably fail for the unchecked version of the same.

The test currently has these checking at .similarity(0.9). Increasing similarity is generally a bad idea when the pattern involved contains text.  I had to reduce similarity to (0.6) in both patterns to get this to work.

**Comment by spronoza** [comment]
Reopened due to UI updates
