### ISSUE TITLE
Fix disable_web_search_awesomebar test

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris_firefox#3526]
This test doesn't seem to be going to Mozilla support as expected early on in the test.
 Please investigate and fix

**Comment by pavelciapa** [comment]
Fails on lines 49, 73 on osx

**Comment by pavelciapa** [comment]
Found mismatches with test description. Updating steps

**Comment by pavelciapa** [comment]
Fix intermittent fail, minor Python logic

**Comment by tracywalker** [comment]
This hasn't failed in the past week on any platform.
