### ISSUE TITLE
Fix awesomebar_search_after_user_input test case

### ISSUE THREAD

**Issue by dbakaev** [mozilla/iris_firefox#3567]
Fix awesomebar_search_after_user_input test case for win7

**Comment by pavelciapa** [comment]
Fails on osx

Twitter icon is clicked while loading

![image](https://user-images.githubusercontent.com/45387203/63606172-fa946c80-c5be-11e9-8511-40dffdef0f24.png)
![image](https://user-images.githubusercontent.com/45387203/63606183-008a4d80-c5bf-11e9-80ae-beec6a03d448.png)
