### ISSUE TITLE
Failed tests mark as Errors during test run under Win 7/10

### ISSUE THREAD

**Issue by pavelciapa** [mozilla/iris_firefox#3575]
When running 1 single test that **fails** in console posts failed:

![image](https://user-images.githubusercontent.com/45387203/62278868-76741c80-b438-11e9-927f-1ec9ccc7265b.png)

but in json file shows that it is error: 

![image](https://user-images.githubusercontent.com/45387203/62278795-504e7c80-b438-11e9-8baf-d26591043e95.png)

**Comment by tracywalker** [comment]
This is a core issue, please file it in mozilla/iris repo

**Comment by pavelciapa** [comment]
https://github.com/mozilla/iris/issues/510
