### ISSUE TITLE
Fix bookmark_from_private_browsing test

### ISSUE THREAD

**Issue by dbakaev** [mozilla/iris_firefox#3626]
Fails on win7 due to absent timeouts

**Comment by spronoza** [comment]
@tracywalker The name of this test not really corresponding to the steps which are performing. And there is no test case with 4155 id on TestRail. Is it relevant test case?

**Comment by tracywalker** [comment]
This test ended up 'orphaned' in TestRail.  We probably cover some variant of elsewhere.  Please delete it from the test repo. Thanks.
