### ISSUE TITLE
Fix one_off_searches_displayed_in_awesomebar test  

### ISSUE THREAD

**Issue by pavelciapa** [mozilla/iris_firefox#3636]
Intermittent failure on osx
reason: incorrect` duck_duck_go_one_off_button `for retina/non-retina

**Comment by pavelciapa** [comment]
@mwobensmith 
when running on retina osx, it searches for normal res .png image, while there is @2x image in folder. Only when .png image is deleted, it starts looking a @2x. 
Is it a core issue?

**Comment by tracywalker** [comment]
blocked_by #3845

**Comment by tracywalker** [comment]
no longer failing on OSX
