### ISSUE TITLE
Hide all windows after test execution

### ISSUE THREAD

**Issue by paulprokhorovmoz** [mozilla/iris_firefox#3698]
Implement hiding all windows after test execution

**Comment by tracywalker** [comment]
Please explain what you mean by hide all windows?  Are you talking about non-Firefox windows?

**Comment by paulprokhorovmoz** [comment]
Yep, such hiding could prevent rare situation when other app cover part of the Firefox instance

**Comment by tracywalker** [comment]
Ok,  whatever you implement, please don't make it try to close all windows after each test case is finished during a test run.  I think, for test run expediency, it would best to try closing unexpected windows only after an individual test failed or errored.

**Comment by tracywalker** [comment]
Matt fixed the shut down method to ensure Firefox is killed, if it was closed cleanly.  This isn't needed.
