### ISSUE TITLE
Fix one_click_search_engines_list_can_be_reordered

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris_firefox#3728]
This test is failing on daily runs with ```The drag and drop successfully performed.```.  I confirmed the failure locally.

**Comment by imskr** [comment]
Can I work on this issue?  Please assign

**Comment by imskr** [comment]
How can I setup this locally?

**Comment by imskr** [comment]
I am getting error while installing packages using `pipenv install`
Traceback timeout error

**Comment by pavelciapa** [comment]
> 
> 
> I am getting error while installing packages using `pipenv install`
> Traceback timeout error
> 
> OS: Ubuntu 16.04

Did you tried to lanch `pipenv shell `after this error message?

Full error message would be appreciated

Try to restart machine, and do `pipenv install` again

**Comment by imskr** [comment]
Yes i tried `pipenv shell` after this error and it ran successfully but then when i ran `iris firefox` it says no command 'iris' found!

**Comment by pavelciapa** [comment]
> 
> 
> Yes i tried `pipenv shell` after this error and it ran successfully but then when i ran `iris firefox` it says no command 'iris' found!

please share screen of terminal where you got error.

**Comment by tracywalker** [comment]
This hasn't failed in the past week on any platform.
