### ISSUE TITLE
Failed tests ran on 69 beta (macOS 10.13)

### ISSUE THREAD

**Issue by MarisBogdan** [mozilla/iris_firefox#3750]
I ran a couple of tests on macOS 10.13 that will cover a bunch of our P1 areas and I had 7 Failed and 4 Errors. Since there are 11 in total I figured I'll log only one issue for all of them.
- bookmark_import_from_html
- change_bookmark_name
- download_cancel_retry
- download_paused_unpaused
- download_warnings_customized_or_disabled_from_the_ui
- malicious_warning
- potentially_unwanted_app
- uncommon_warning
- user_is_prompted_when_trying_to_close_the_private_window_while_downloading
- navigation_works_properly
- restored_for_dirty_profile

I have stored debug images for all the tests in [gdrive](https://drive.google.com/open?id=1jdLQ1u9gpPUoMyg15gMF21jWhaDtovw5)

**Comment by MarisBogdan** [comment]
Yes I am testing on a retina 13 inch display. I ran `iris -a -k` and ran only those 11 tests that previously failed. Only one of them passed (user_is_prompted_when_trying_to_close_the_private_window_while_downloading) the rest are still failed/errors.

**Comment by tracywalker** [comment]
Ok, we have known issues with retina. At the moment, we're working cleaning up non-retina first.  If you have access to an non-retina screen, please use that.  (note: When Iris goes into CI production, retina will not be supported there.)

**Comment by tracywalker** [comment]
I ran the 11 failing test cases on non-retina and saw 3 tests fail and one test error.  There are issues on file for those already.  I will file an issue to investigate why we're seeing retina specific test case failures.
