### ISSUE TITLE
Fix search_bar_can_be_added

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris_firefox#3762]
The end of this test that performs a search can be removed.  We test this functionality over and over in other tests.  Let's just check that the search bar is added to the location toolbar from preferences (check the search bar is there, that's all)

**Comment by pavelciapa** [comment]
Should we change test description first? [https://testrail.stage.mozaws.net/index.php?/cases/view/143589](https://testrail.stage.mozaws.net/index.php?/cases/view/143589)

**Comment by tracywalker** [comment]
> Should we change test description first? https://testrail.stage.mozaws.net/index.php?/cases/view/143589

Done.
