### ISSUE TITLE
Investigate why there is increased failure on osx retina vs non-retina test runs

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris_firefox#3769]
Is it a similarity problem? Are @2x images not being correctly converted across the project?  Whatever it is, since we switched to Iris2,  retina test runs have a 2-3 times higher test failure rate than non-retina test runs.

**Comment by pavelciapa** [comment]
Retina failures counts ~90 while non retina ~30

Reasons are outdated UI patterns.

Also found strange **@2x** behaviour on retina described here - _Originally posted by @pavelciapa in https://github.com/mozilla/iris_firefox/issues/3636#issuecomment-519938945_

**Comment by tracywalker** [comment]
I ran the zoom_indicator suite 
on retina: 1 passed, 18 failed and 6 error.
on non-retina 17 passed, 8 error.  (I have patch to fix 7 of those 8 in one go). 
So, on non-retina will be 25 pass, 1 error.

Point is there is a drastic difference in retina vs non-retina test run.

This is a core issue of some sort.  I'm going to close this and file issue there.
