### ISSUE TITLE
Fix websites_using_extended_validation_properly_loaded_and_depicted.py test

### ISSUE THREAD

**Issue by spronoza** [mozilla/iris_firefox#3801]
@tracywalker Test case https://testrail.stage.mozaws.net/index.php?/cases/view/3952 was outdated for firefox-70.0b5-build1. Update needed.

**Comment by tracywalker** [comment]
@spronoza Please explain the details of this test being 'outdated';  is the functionality gone oir changed and in what way.  Thanks

**Comment by spronoza** [comment]
"The owner of the domain is highlighted in green, next to the URL, e.g. Mozilla Foundation (US)."
Now there is no owner of the domain next to the URL. Should we just remove that check?

**Comment by tracywalker** [comment]
Hmmm, please confirm with the test author that this new behavior is expected.

**Comment by spronoza** [comment]
It is expected. Extended Validation (EV) indicators was removed.
