### ISSUE TITLE
Fix error in download_manager_utls.py causing throttling to fail to be set

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris_firefox#3802]
The `select_throttling(option)` function is failing to find `'network.png'`

Please investigate and fix this pattern.

**Comment by pavelciapa** [comment]
Cannot reproduce this failure.

Update pattern network.png for all platforms

**Comment by tracywalker** [comment]
> Cannot reproduce this failure.
> 
>     * Update pattern network.png for all platforms

Yes,  I filed this based on errors reported in irishub against OSX on 2019-09-09.  The error hasn't appeared since.
