### ISSUE TITLE
Fix ocr test

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris_firefox#3813]
`create_region_from_image(NavBar.HAMBURGER_MENU)` is no longer valid.  I'll update the test to use `create_region_for_hamburger_menu()`

**Comment by tracywalker** [comment]
This is failing, I think, because the test clicks the hamburger menu button before the call to create_region_for_hamburger_menu(), which needs the hamburger menu button to be in an unhovered state.

**Comment by spronoza** [comment]
There is 'Options' instead 'Preferences' in the 'hamburger menu' on Windows.
