### ISSUE TITLE
Fix about_firefox_controls test

### ISSUE THREAD

**Issue by pavelciapa** [mozilla/iris_firefox#3821]
Update pattern for Firefox 70

**Comment by pavelciapa** [comment]
@tracywalker according to test description https://testrail.stage.mozaws.net/index.php?/cases/view/120465 we have to click on all controls.

> 4 | Click on all the controls available.

We are checking only close button, as others are complicated to test. 

I think we agreed this earlier. Those this make sense?

**Comment by tracywalker** [comment]
Yes,  just make the Iris Firefox test work as it is; close only.
