### ISSUE TITLE
Iris Firefox test runs in CI are occasionally timing out due to an internalerror in mozdownload

### ISSUE THREAD

**Issue by KWierso** [mozilla/iris_firefox#3882]
With Iris running against CI builds in taskcluster, I'm seeing some occasional task failures that are caused by Iris's use of mozdownload to fetch information about Firefox builds.

An example of the failure is https://treeherder.allizom.org/logviewer.html#/jobs?job_id=267613848&repo=try&lineNumber=762-803

I'm not sure what's causing the error, exactly. Other iris test runs on the same push (using the same build, started approximately at the same time) successfully run just fine. My working theory is that it's a timing issue where mozdownload tries to fetch this info right as new Nightlies are being created so the information is only partially available, but that's just a guess.

Couple sub-issues here:
1. When this error happens, it doesn't cause the command to stop running. The task just stalls out until taskcluster sees the task has exceeded the max-run-time (currently 150 minutes) and kills it for a max-run-time-exceeded error. These errors happen only a few minutes into the task run, so that's a lot of unnecessary machine time wasted just sitting around. It would be better if Iris could catch this internalerror from mozdownload and do something else within Iris. Would catching the erro and returning `None` work, here? I'm not sure exactly what we're trying to find with mozdownload when I've passed in a CI build directly. I think it's [this function](https://github.com/mozilla/iris_firefox/blob/326fb7488c61c10b66789d2fe177f0797e2a972a/targets/firefox/firefox_app/fx_browser.py#L513-L525) that's triggering the error?
2. Do we really need to fetch anything from archive.mozilla.org when we're passing in a CI build? Can this whole function be skipped when we're in `--treeherder` mode or if Iris sees that we've passed in a path to a local build?

**Comment by mwobensmith** [comment]
1. Yes
2. Yes

**Comment by mwobensmith** [comment]
More info:

There are update tests that need to know this value, and these will be run in Treeherder mode. However, I can try to make the function more resilient as you suggest. Also, I can delay that network request until the test actually needs it to avoid stalling the run up until that point.

**Comment by KWierso** [comment]
I don't know if it matters too much (unsure exactly what the update tests do), but the CI builds don't have updates enabled. Checking for updates will never actually show updates available.

**Comment by tracywalker** [comment]
The update test are special beasts that don't really run the same way as a standard Iris test.. The update tests fetch and install a past version of Firefox. Then Iris launches that build and triggers an update. Finally, Iris checks the version to ensure the build updated to the expected latest version.  We used the function ` get_firefox_latest_version()` to make that final check.  

I don't know why this would be happening in a standard test run.  The update tests are all disabled as they are not meant to be run along side standard Iris tests.

**Comment by mwobensmith** [comment]
@KWierso The update tests are, in all likelihood, not going to be run in Treeherder. Let me consult with @tracywalker about this. Either way, we'll address this so that you don't see error(s). :D

**Comment by mwobensmith** [comment]
OK, so since we don't intend to run update tests in Treeherder anytime soon, I will take that into account with a fix. Shouldn't be hard.

**Comment by mwobensmith** [comment]
I moved `latest_version` out of the constructor, which always gets called regardless of mode/build that we're testing. So, for normal runs, we won't look this up anymore.

It is now a property within the `FirefoxApp` class, and in turn, it calls the static `FirefoxUtils.get_firefox_latest_version` only when queried. AFAICT, this only happens in the update tests.
