### ISSUE TITLE
Test case: A hyperlink can be opened in a new tab

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris_firefox#3909]
https://testrail.stage.mozaws.net/index.php?/cases/view/134444

**Comment by tracywalker** [comment]
| Step | Expected Result
-- | -- | --
1 | Launch Firefox. | Firefox launches successfully.
2 | Access the following [website](https://en.wikipedia.org/wiki/United_States). | The webpage is successfully displayed.
3 | Right click on the first link and left click the Open link in New tab option. | The selected link is opened in a new tab.

**Comment by imskr** [comment]
Which file should I make changes in for this issue.

**Comment by tracywalker** [comment]
This is a new test case.

**Comment by imskr** [comment]
Do i need also test case id and number ? I'm using this guide as reference: https://github.com/mozilla/iris_firefox/wiki/Test-Case-Creation-Guide

**Comment by tracywalker** [comment]
Yes,    in the details, `@pytest.mark.details( `   please include the test case ID and the test suite ID as follows.
```
test_case_id="134444",
test_suite_id="2103",
```

Also, a new directory for this will have to be created at  iris_firefox/tests/firefox/tabbed_browser

**Comment by imskr** [comment]
There are images section too in each test case directory. How should I get that for this test?

**Comment by tracywalker** [comment]
Yes,  directories for each platform to maintain images.  Please follow the structure of other test groups.
