### ISSUE TITLE
Update target/nightly/icon.png for CC.

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris_firefox#3963]
Control Center has an Icon for the targets.  Currently, the Nightly target has a regular Firefox icon. This issue is about putting into place a version of the purplish Nightly Firefox icon.

**Comment by imskr** [comment]
I have to replace the target/nightly/icon.png with purplish nightly icon

**Comment by tracywalker** [comment]
Yes, it has to be transparent and about 80x80

**Comment by tracywalker** [comment]
Ack. During my review I didn't notice which icon was changed. We have them flipped flopped.  Nightly icon is in Firefox Target and Firefox icon is in Nightly target. I'll fix this right away,.

**Comment by tracywalker** [comment]
done

**Comment by imskr** [comment]
Sorry, I didn't notice. Thanks!

**Comment by imskr** [comment]
I would be happy to fix if there are any easy test case issues. I will need a little bit of reference for that. @tracywalker
