### ISSUE TITLE
implement flake8 linting in travis

### ISSUE THREAD

**Issue by kimberlythegeek** [mozilla/iris_firefox#3984]
implement travis CI and run the flake8 linter on each PR

**Comment by imskr** [comment]
I would like to work on this. Please assign

**Comment by tracywalker** [comment]
imskr.  Kimberly has already implemented this in iris core and already has patches in progress for here.

I'd be willing to help you find other issues to work on if you're not interested in test case work.

**Comment by imskr** [comment]
@tracywalker is there any beginner issue for test case or any other?

**Comment by tracywalker** [comment]
Sorry about the chatter here, Kimberly.

@imskr please take a look at issue #3963.
