### ISSUE TITLE
Fix perform_a_search_using_a_one_off for treeherder Nightly

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris_firefox#4008]
Test is failing after restart in line 49.  Looks like it's not loading up the local Firefox test site page.

**Comment by imskr** [comment]
I need a little help with this. I want to fix this issue.

**Comment by tracywalker** [comment]
@imskr The last few issues I filed are difficult because we have to debug from a remote system.   As such, I have assigned them to myself so I can work with Mozilla developers that own the remote systems. 

Please take a look at https://github.com/mozilla/iris_firefox/issues/3909.  This one should be a good starter test case to work on.

**Comment by tracywalker** [comment]
This test is failing in a different way in manually triggered try run than in ci-triggered run.  Investigating both, though unable to reproduce locally.

**Comment by tracywalker** [comment]
This is fixed on Windows.  However, it continues to fail on Linux in CI environment.  Unable to reproduce locally. I'll do my best to trace through test to determine a solution for Linux.

**Comment by tracywalker** [comment]
This is failing intermittently on Win10 and still failing on Linux in taskcluster runs.  On Linux it's failing to verify a page was bookmarked.  On Windows, it appears to be failing to verify the browser was restarted.
