### ISSUE TITLE
Fix pdf_navigation_works_properly for treeherder Nightly

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris_firefox#4009]
Failing in the key navigation to the right part of the test at lines 67-68. The keyboarding commands are probably happening to quickly for the slow responding machine.  Other areas later in the test probably will fail for similar reason.  I'll slow things down.

**Comment by tracywalker** [comment]
My fixes for this didn't work in CI environment.  Plus, on Linux, this test is failing later in trying to find an option in the pdf tools menu.

**Comment by tracywalker** [comment]
Fixed the Linux issue.   I cannot reproduce the following on my local Win10 hardware.

The Win10 problem appears to be an issue with the virtual machine not accepting RIGHT key.  I can observe it accepting UP and DOWN keys immediately before and after the test tries to key RIGHT (which should make the PDF scroll down an entire page), but the page isn't scrolled.  I'll ask @m8ttyB if the is any way this can be investigated in the test environment manually.

**Comment by tracywalker** [comment]
Failure in production on Linux looks like pattern similarity in the tools menu.  I decreased similarity to fix the first failure, but can only wait for next test run, after uplift of this fix, to see if other menu items will also need reduced similarity.

**Comment by m8ttyB** [comment]
We should investigate attaching to a remote session on Try. I'll dig into the documentation for taskcluster; figuring out the steps and also what level of commit access is required to to do this.

**Comment by tracywalker** [comment]
My instinct is that the virtual keyboard in the VM is swallowing this particular key stroke. If we haven't sorted out how to get an interactive session up and running, to confirm/deny my hunch, by the next merge to master, on Tuesday or Wednesday, I'll temporarily disable the offending portion of the test.

**Comment by tracywalker** [comment]
Basic test of left and right keystroke works in the url bar. 

Maybe this pdf navigation test needs to ensure the content has focus. Seems unlikely as last keystroke  Key.UP was accepted and nothing else occurred other than an Iris pattern assert.  I guess it's worth a try clicking in the content area before Key.LEFT.

**Comment by tracywalker** [comment]
This still needs work for Linux.  Looks like more pattern similarity issues.
