### ISSUE TITLE
Not correct total time in terminal log after run

### ISSUE THREAD

**Issue by pavelciapa** [mozilla/iris_firefox#4049]
I ran a bunch of tests and got that terminal log doesn't count re-run time, or shows incorrect time of run

I assume that we should count time for re-run in total? 

> ----------------------------------------------------------Test Report----------------------------------------------------------Application: Firefox, Platform: win, fx_version: 70.0, fx_build_id: 20191007220302, channel: beta
> Passed: 1, Failed: 6, Skipped: 0, Errors 1  -- Total: 8                                                Total time: 00:05:39.457

The factical time here is ~15 mins

**Comment by mwobensmith** [comment]
I think the total time is calculated by adding up the execution time of each test case, but is not counting the skipped ones, as @pavelciapa has stated.

However, it is also not counting the time it takes to start Iris, download/install Firefox, etc. Should we change "total time" to be equal to the actual time between start/stop of Iris? I think so, but would like an opinion before I do the work.

**Comment by tracywalker** [comment]
I was chatting with Pavel about this before he filed this issue.  I think he believes that tests that fail and are re-run are only counting time from one run of the three tries.

It seems like a good idea to capture entire run time for a test run and also log individual test run time.  For final run summary, show total run time, start to end.  I have no opinion about whether or not to include fetching and installing the Firefox build.

**Comment by pavelciapa** [comment]
Agree with @tracywalker

**Comment by mwobensmith** [comment]
I do think "total time" should be from start to finish, including dealing with the Firefox build. I will make it so.

**Comment by mwobensmith** [comment]
This is a core bug, so I filed an issue there and will close this one.
