### ISSUE TITLE
enable iris_firefox tests to run in docker

### ISSUE THREAD

**Issue by kimberlythegeek** [mozilla/iris_firefox#4061]
- [ ] update documentation to include docker usage
 - [ ] run (a subset of?) firefox tests in travis using docker

**Comment by imskr** [comment]
can i take this issue ?

**Comment by tracywalker** [comment]
@imskr This issue already assigned and being worked on.  Any luck with the test I pointed you to?

**Comment by imskr** [comment]
working on it. @tracywalker

**Comment by kimberlythegeek** [comment]
currently not in progress. this solution would only work for versions of linux that have available docker images (and possible windows, there is a docker image for that now)
