### ISSUE TITLE
Reduce white space introduced by the Black code formatter

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris_firefox#4081]
My first request is to not add white space where () are involved.  It looks like it is using '(' as a potential wrap point.

Black code formatted:
```       
        rotate_clockwise_button_pattern = Pattern(
            "rotate_clockwise_button.png"
        ).similar(0.6)
        pdf_file_last_page_contents_pattern = Pattern("last_page_contents.png")
        go_to_last_page_button_pattern = Pattern("go_to_last_page_button.png").similar(
            0.6
        )
```

Expected out put is the more easily read as written:
```
        rotate_clockwise_button_pattern = Pattern("rotate_clockwise_button.png").similar(0.6)
        pdf_file_last_page_contents_pattern = Pattern("last_page_contents.png")
        go_to_last_page_button_pattern = Pattern("go_to_last_page_button.png").similar(0.6)
```

And additional request, once this and any more formatting rules changes are submitted, is to run Black against the entire project. The project is not consistent in formatting because Black is only running against files that are being touched. Cleaning up the entire project will make future code reviews simpler/clearer.

**Comment by kimberlythegeek** [comment]
while parentheses are the wrap points, this may be a line length issue, since it doesn't perform it on all cases

**Comment by kimberlythegeek** [comment]
looking, the line length is set to 120, but there are only 91 characters in the line:
```
        go_to_last_page_button_pattern = Pattern("go_to_last_page_button.png").similar(0.6)
```

**Comment by kimberlythegeek** [comment]
https://black.readthedocs.io/en/stable/the_black_code_style.html#how-black-wraps-lines

**Comment by tracywalker** [comment]
Ok, I'd rather Black not do line wrap corrections, since this is the result.  The look and readability of our pattern declarations is aweful with the Black auto-corrections.

**Comment by kimberlythegeek** [comment]
Hi--I'm actually working on this right now

**Comment by kimberlythegeek** [comment]
I found a way to change the line length as a setting in pycharm, but it requires configuring black as a file watcher

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/18633586/68887220-d89a1a00-06d5-11ea-9b13-cff74db2aeff.png">

instructions are here: https://black.readthedocs.io/en/stable/editor_integration.html#pycharm-intellij-idea
with the exception: Arguments should be set to `$FilePath$ -l 120`

in the tox.ini file, `max-line-length` is set to 120 but black doesn’t appear to follow that. I believe its supposed to
