### ISSUE TITLE
Investigate browser size on restart in taskcluster for Windows

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris_firefox#4095]
In Nightly test runs on Windows, the Iris test, previous_session_can_be_restored_from_firefox_menu fails after the browser restart because it appears that the browser is resized too large, which pushes the url toolbar off the screen.  The first functional step after restart is to open the hamburger menu. However, Iris can't find the button on the url toolbar, because it's not on screen.

It feels like a bug in Firefox not resizing correctly on restart, but this works correctly on actual hardware locally.  Is the taskcluster run also headless hear on Windows?  Can we control window size programatically on browser restart?

**Comment by tracywalker** [comment]
MattB or MattW can either of you explore this in the actual taskcluster environment?  

<img width="1306" alt="normal_vs_restart" src="https://user-images.githubusercontent.com/1233923/67322478-ad594c00-f4d6-11e9-8331-e2ab14092b4e.png">

The top left image shows the browser with toolbars at first launch.  The bottom right image shows what Iris is scanning after the browser has restarted. Notice no toolbars.

**Comment by m8ttyB** [comment]
From a Taskcluster perspective, as we discussed, ping #taskcluster. For introspecting live sessions on Taskcluster we can use the self[ provisioning instructions for Windows instances](https://wiki.mozilla.org/ReleaseEngineering/How_To/Self_Provision_a_TaskCluster_Windows_Instance).

**Comment by tracywalker** [comment]
Wonders if is possible have Iris force the browser to open to a set size on restart?

**Comment by tracywalker** [comment]
I fixed this, in the test, by resizing the window before browser restart. Then after restart re-maximized the browser window.
