### ISSUE TITLE
Add a windows manager to the Linux VM for nightly test runs

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris_firefox#4096]
Linux is operating without any desktop window manager. Linux tests are failing do to inability to maximize the browser after launch.  Iris tries to do this by using the window controls, which aren't there.

Wes tried on Friday to add a windows manager (I don't know which one).  It didn't work in try runs, there were no window controls.  I think we want to make sure the window manager is the same as on our Ubuntu 16.04 machines.  Wes mentioned he thinks that is Unity.

**Comment by m8ttyB** [comment]
For debug purposes, you can use this image locally. It matches what we're using in production (Taskcluster).

https://hub.docker.com/r/m8ttyb/debian10-test-iris

**Comment by tracywalker** [comment]
A little research indicates Ubuntu 16.04 uses Unity and Debian uses Gnome desktop.  It should be possible to install Unity on Debian.  If successful installing that into the Docker environment, that should solve the problem for Iris tests on Linux.

**Comment by tracywalker** [comment]
Also check to see if headless mode is somehow interfering by disabling the default desktop manager.

**Comment by tracywalker** [comment]
MattB or MattW can either of you explore this in the actual taskcluster environment?

**Comment by m8ttyB** [comment]
I'd suggest we use the above docker image, it's a copy of what's running in production.

**Comment by kimberlythegeek** [comment]
can we add a traceback to this bug? what test(s) does this error occur on?

**Comment by tracywalker** [comment]
At the start of every test, the browser is opened, we confirm that it is. Then Iris sends keystroke combination to maximize the window.  The function, maximize_window(), that does this, doesn't have any error checking. In test runs on taskcluster, Iirs fails to maximize the window and just goes on until some other portion of the test that does rely on the window being maximized fails.  Not all of the tests were hitting a fail point.  In latest changes, I have removed all dependencies on window being there in the nightly target. As such, no tests are failing because of lack of window on the browser..

**Comment by kimberlythegeek** [comment]
for clarity: we are already using a _window_ manager, `xvfb`, what we need is a desktop manager

**Comment by m8ttyB** [comment]
I did an experiment in a docker container and was able to grab a screenshot. Notice, this is using Fluxbox and not gnome-shell. Firefox also didn't properly start.

I _think_ we want the later, though this begins to show that we're approaching a possible solution.

 ```
export DISPLAY=:1
Xvfb :1 -screen 0 1024x768x16 &
 fluxbox &
firefox &
gnome-screenshot --display=:1 --file=screenshot.png
```

![screenshot2](https://user-images.githubusercontent.com/63193/69192766-7d579580-0ae2-11ea-960d-79b4baf120a5.png)

**Comment by m8ttyB** [comment]
I've scripted this to run in docker, saving the screenshot to your dev environment's local filesystem (technically mounts the entire working dir of `iris_firefox`). This will drop you into a bash prompt inside the running docker container where you can execute commands. The Firefox tests will not run unless `pipenv install` && `pipenv shell .. etc` are run.

There's more to do, but this hopefully provides an easy canvas to experiment with. I believe our next step is to explore substituting `gnome-shell` for `Fluxbox`.

Code is here --> [add_docker branch](https://github.com/m8ttyB/iris_firefox/tree/add_docker)

To run this, execute commands via `docker-compose`:

0. cd `iris_firefox` && `docker-compose build`. The build will take some time while `leptonica`, `tesseract`, and other dependencies are installed.
1. You only need to run `docker-compose build` once to build the container locally. Once built you can skip step `#2`.
2. Start the container and enter it via a bash shell - `docker-compose run iris bash`
3. Start Xvfb, Fluxbox, and take a screenshot - `./docker/experiment_headless_iris.sh`.
4. Inspect your local directory `iris_firefox/` and `screenshot.png` should be present.
5. Type `exit` to shutdown and leave the docker container.
