### ISSUE TITLE
Iris code root not found causing taskcluster runs on Win10 to fail

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris_firefox#4103]
Please see log at https://taskcluster-artifacts.net/NnYqTuPyR4CHcKQ688mb4g/0/public/logs/live_backing.log.  specifically:

```
Desired target: nightly
[task 2019-10-23T12:26:42.649Z] Desired module: targets.nightly.main
[task 2019-10-23T12:26:42.649Z] Path not found: c:\users\task_1571830546\.virtualenvs\iris_firefox-jaewvgmg\lib\site-packages\targets\nightly
[task 2019-10-23T12:26:42.649Z] This can happen when Iris can't find your code root.
[task 2019-10-23T12:26:42.649Z] Try setting these environment variables:
[task 2019-10-23T12:26:42.649Z] 	set IRIS_CODE_ROOT=%CD%
[task 2019-10-23T12:26:42.649Z] 	set PYTHONPATH=%CD%
```

**Comment by m8ttyB** [comment]
That's curious, the only code change was a bump to revision `d52a2db666ee199261a75e598870ec2c0c0ea36e` via [bug 1589763](https://bugzilla.mozilla.org/show_bug.cgi?id=1589763). Let's check if this is a regression in our code or a change of state in Taskcluster that we're unaware of.

**Comment by kimberlythegeek** [comment]
I believe this was a change made to support my work in docker. The project root was not being set correctly. 

My suggestion was to enforce the use of an environment variable in a config file, set to a default value, that the user can change if desired, but that solution wouldn't work for taskcluster. 

I'll look into the code a bit, maybe find a more reliable way to find project root for taskcluster builds.

what is the code root supposed to be @m8ttyB , do you know?

**Comment by m8ttyB** [comment]
> What is the code root supposed to be?

Truthfully I don't know off the top of my head. I'm looking for a regression range, I've reverted the pinned revision of `iris_firefox` to [commit 614bf07e14769552a533798fb3ccf8a7c1e7f23d](https://github.com/mozilla/iris_firefox/commit/614bf07e14769552a533798fb3ccf8a7c1e7f23d) and am running the job on Try Server. Reverting effectively pins `moziris = "==0.6"`
https://treeherder.mozilla.org/#/jobs?repo=try&revision=afbece188e0c6419f817baa8c227fc1737dae8f2&selectedJob=272586882

**Comment by m8ttyB** [comment]
Based on the outcome of the above test run (job is still running, but made it past the failure point we're seeing in prod) - [Live log here](https://tools.taskcluster.net/groups/IoQhPChySTSrQgav2csieg/tasks/OxfNK9teQiG3UrfGJn2LDQ/runs/0/logs/public%2Flogs%2Flive.log) - the regression was introduced when we [pinned moziris ==0.7](https://github.com/mozilla/iris_firefox/commit/d52a2db666ee199261a75e598870ec2c0c0ea36e).

[Bug 1590795](https://bugzilla.mozilla.org/show_bug.cgi?id=1590795) filed to revert the toolchain to the previous commit revision.

**Comment by mwobensmith** [comment]
The code root should be equal to the location of the `tests` and `targets` directories.

**Comment by mwobensmith** [comment]
Also, this works for me locally. I don't understand what it is about the Taskcluster config that differs. 

* Does the Taskcluster config use `pipenv`?
* Do you set the environment variables `IRIS_CODE_ROOT` and/or `PYTHONPATH`?

**Comment by m8ttyB** [comment]
Tests are configured to run as such [run-iris-windows.sh](https://searchfox.org/mozilla-central/source/taskcluster/scripts/iris/run-iris-windows.sh). Give me a few moments and I can start a debug build

**Comment by m8ttyB** [comment]
Posted this in #qa-automation, but forgot to update the issue. Posting for posterity.

Build w/ debug options enabled running here, this is for the ci tests which complete much faster than the nightly build validation suite. https://treeherder.mozilla.org/#/jobs?repo=try&revision=26db699691113f9173c1ec227761a8d117573ff3

Full NBV suite run here https://treeherder.mozilla.org/#/jobs?repo=try&revision=af1605970bf8a60dc069c2e35578213e6f10677a

**Comment by m8ttyB** [comment]
Pushing the reversion to lando now --> https://lando.services.mozilla.com/D50244/

**Comment by m8ttyB** [comment]
@mwobensmith 

wrt 
> Do you set the environment variables IRIS_CODE_ROOT and/or PYTHONPATH?

No, these do not get set by the test job.

**Comment by mwobensmith** [comment]
@m8ttyB Is this still an issue?

**Comment by m8ttyB** [comment]
The most recent failure on Win10 suggests that we're still seeing an error that looks similar
https://firefoxci.taskcluster-artifacts.net/RzCX0S4CQji02_7LWBztqQ/0/public/logs/live_backing.log

**Comment by m8ttyB** [comment]
@mwobensmith Here's a log from this morning's Win10 run. Hope the additional debug information is useful

https://firefox-ci-tc.services.mozilla.com/tasks/RzCX0S4CQji02_7LWBztqQ/runs/0/logs/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FRzCX0S4CQji02_7LWBztqQ%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log#L2257-2276

**Comment by m8ttyB** [comment]
If I'm reading this correctly, I do see some path curiosities with `\` vs '/`. We're setting up the environment and executing the tests from a shell script, would this be causing those errors?

https://firefox-ci-tc.services.mozilla.com/tasks/RzCX0S4CQji02_7LWBztqQ/runs/0/logs/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FRzCX0S4CQji02_7LWBztqQ%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log#L2215-2260

**Comment by m8ttyB** [comment]
I'm investigating this via the taskcluster side, we'll see what the level of re-work is. Currently Iris is being invoked via a bash script https://searchfox.org/mozilla-central/source/taskcluster/scripts/iris/run-iris-windows.sh
