### ISSUE TITLE
Fix search_bar_can_be_enabled_disabled

### ISSUE THREAD

**Issue by spronoza** [mozilla/iris_firefox#4123]
The search bar is continue to displays in New Private Window after disabling.
![image](https://user-images.githubusercontent.com/46671906/67697642-8c4e9a80-f9b1-11e9-8bac-96fc6c8a1915.png)

**Comment by tracywalker** [comment]
If this is reproducible manually, it sounds like a Firefox bug.

**Comment by tracywalker** [comment]
Wait. what setting are you changing?  The picture you posted is not of the search bar. The search bar appears to the right of the url bar if enable.

**Comment by spronoza** [comment]
It was called like that in the TestRail. But probably right name it is the "Web search bar". The "Web Search" option on the about:preferences page was changing.

**Comment by tracywalker** [comment]
The test is for the search bar that can be added, via pref, to the location bar.  This test is not about the page content search field.

**Comment by tracywalker** [comment]
Sorry.  my mistake.  This does appear to be about the page content. It looks like a a bug.  Let me bring it up in channel.

**Comment by ranjit-exalt** [comment]
Assigning it to Tracy as it is on hold for RelQA's assessment. 

@tracywalker: Please assign this issue to me once we have action items to fix this.
