### ISSUE TITLE
Windows 10 fails to find initial Iris "eyes" pattern

### ISSUE THREAD

**Issue by ashughes1** [mozilla/iris_firefox#4127]
Running a testrun on Windows 10 all tests are erroring out as it appears the initial pattern matching for the Iris "eyes" graphic is failing, despite it being on the screen. Debug images and log are available on [Google Drive](https://drive.google.com/open?id=1ripvMDOArwInRnMXSj9tzhZsgg9QxTyZ).

This problem occurs with every single test.

**Comment by tracywalker** [comment]
Anthony,  what screen resolution is that machine set to?  

Recommended supported screen resolution is 1920 x 1080 for Windows.

**Comment by ashughes1** [comment]
You were right, screen was set to 4K resolution. I dialed it down to 1080p and it's working correctly now.
