### ISSUE TITLE
Create a new canned profile for use with test around Higlights and future new:tab tests

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris_firefox#4157]
We're in need of a new canned profile that has download history and pages added to Pocket.  Currently, Ranjit is creating preconditions as part of his test case development in issue #3115.  We have a few more in line that may need pre-existing data in a profile.  RelQA has also listed over 100 test cases on the about:newtab page and Pocket that we may be required to automate.  It would be wise of us to get out in front and have a pre-canned profile available for current development and for potential future use.

Matt, can I work with you to get this put in place.  I'll need to do a little digging into what information/data is likely needed in the future tests.

**Comment by ranjit-exalt** [comment]
@mwobensmith : It would be nice if we create a profile which will have a selection of sites that you’ve saved (download, saved to pocket or bookmark) or visited. So basically we need a profile where all four following section of sites are present: 
1. Visited Pages
2. Bookmarks
3. Most Recent Download
4. Pages Saved to Pocket

**Comment by tracywalker** [comment]
I think this isn't going to work with a canned profile for #3 and we currently aren't supporting creating a pocket account.    I spoke with Matt and we think you can do #1 and #2 with the TEN_BOOKMARKS profile.  You'll have to download a file as part of the test.  The pocket portion of the test will have to be skipped for now.
