### ISSUE TITLE
Profiles.TEN_BOOKMARKS, is only showing 4 bookmarks in highlights

### ISSUE THREAD

**Issue by ranjit-exalt** [mozilla/iris_firefox#4201]
When I imported the TEN bookmarks profile (Profiles.TEN_BOOKMARKS ) in my test case, while execution-only four bookmarks are displaying in highlights.

![default_highlights_rows](https://user-images.githubusercontent.com/54833244/68781011-21fa5300-065d-11ea-882a-2be15c0dabf0.png)

**If we change the number of rows displayed for highlights from about:preferences#home,**
![change number of row from 1 to 2](https://user-images.githubusercontent.com/54833244/68781115-48b88980-065d-11ea-9478-443f5fd3178c.PNG)
 **Empty highlights boxes are getting added.**
![highlights_with_2_rows](https://user-images.githubusercontent.com/54833244/68781232-79002800-065d-11ea-93d8-90ac3b4c7617.png)

 **Ideally, if we have ten bookmarks, It should display up to 10 bookmarks in highlight boxes based on the number of rows selection. But, it's only showing four, irrespective of the number of rows selected.**

**Comment by tracywalker** [comment]
Discussed this with Ranjit. It feels like a bug in Firefox, but he can only reproduce this with the old Ten_bookmarks profile.  If we reported it as a bug, first thing devs would ask is can it be reproduced in a new profile.  Answer: no. bug closed: INVALID.  

Test developers are  going to have to create content on the fly, when needed for these new tab tests.

**Comment by mwobensmith** [comment]
I think this is a Firefox bug. It would affect users with existing profiles, which IMHO would not qualify it as invalid... in fact, this makes it worse, as it would be a compatibility issue of more concern.

However, it's a cosmetic issue. New bookmarks added at this point will populate those squares.

So, I think we should do a few things:
* File a Bugzilla bug and attach the profile - `ten_bookmarks.zip` - and explain how to see the problem.
* Decide if we really need 10 bookmarks to show up in the new tab > Highlights area, or if we can test with just 4.

**Comment by spronoza** [comment]
The items in Highlights area are Visited Pages not bookmarks. 
![image](https://user-images.githubusercontent.com/46671906/68842584-455de600-06cf-11ea-80a7-e7f3c034a1e9.png)

**Comment by tracywalker** [comment]
Matt, iirc you believe this may actually be a Firefox bug.  Can you zip up the profile and file the bugzilla bug?
