### ISSUE TITLE
Fix failing drag_and_drop test cases for Linux in FxBeta71

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris_firefox#4206]
Over a dozen tests case failing

**Comment by ranjit-exalt** [comment]
All the 14 test cases are failing. I have started issue fixing for the following failed test cases.  Last run report: 

--------------------------------------------Test Report-------------------------------------------------
Application: Firefox, Platform: Linux, fx_version: 71.0, fx_build_id: 20191118154140, channel: beta
Passed: 0, Failed: 14, Skipped: 10, Errors 0  -- Total: 24                                                                                                                                                                                 Total time: 00:31:52.869

**The following tests did not pass:**
drag_drop_html.py
drag_drop_html_private.py
drop_jpeg_image.py
drop_jpeg_image_in_private_window.py
drop_pdf_file.py
drop_pdf_file_in_private_window.py
drop_png_image.py
drop_png_image_in_private_window.py
drop_txt_file.py
drop_txt_file_in_private_window.py
paste_html.py
paste_html_in_private_window.py
paste_image_data.py
paste_image_data_in_private_window.py

**Comment by ranjit-exalt** [comment]
Pull request https://github.com/mozilla/iris_firefox/pull/4242 created.
