### ISSUE TITLE
Fix failing search_and_update test cases for Linux in FxBeta71

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris_firefox#4213]
About ten test cases failing here

**Comment by ranjit-exalt** [comment]
The following 10 test cases are failing:

1. change_the_default_search_engine.py
2. default_search_code_yandex.py
3. keyboard_shortcuts_work_in_search_bar.py
4. middle_clicking_search_results_open_new_tab.py
5. one_off_search_engines_can_be_removed_and_restored.py
6. remove_search_engine.py
7. search_bar_submission_with_no_input.py
8. search_suggestions_are_displayed_in_search_bar.py
9. search_suggestions_can_be_disabled.py
10. search_with_search_engines_keywords.py

I have started issue fixing for the above test cases.

**Comment by ranjit-exalt** [comment]
Pull request created: https://github.com/mozilla/iris_firefox/pull/4234
