### ISSUE TITLE
"Search using Google" text not appearing on hovering search bar 

### ISSUE THREAD

**Issue by ranjit-exalt** [mozilla/iris_firefox#4229]
After modifying "browser.search.widget.inNavBar" as true and navigating to new tab -> search (using "CTRL+K" command) when automation script hovering mouse on search bar "Search using Google" text should appear, but it's not appearing. I have tried this with hover and Mouse().move commands, "Search using Google" text is not appearing. Even I have tried manually in a browser that was launched by Iris, but the text never appeared. 

It's working absolutely fine in the Manual Firefox (Firefox 70.0.1) browser and only creating an issue when the browser is being launched by Iris. Hence it looks like this feature has been removed from 71.011 build.

When hovering on manual browser (Firefox 70.0.1): 
![Manually](https://user-images.githubusercontent.com/54833244/69134812-1c2dc300-0ade-11ea-8ff8-94c2a67d95cd.png)

When hovering on browser launched by Iris (Firefox: 71.011: 
![Using iris](https://user-images.githubusercontent.com/54833244/69134800-16d07880-0ade-11ea-8042-dec8a13d268a.png)

Test case "keyboard_shortcuts_work_in_search_bar.py"  ( test_case_id="4278", test_suite_id="83") is failing due to this issue.

**Comment by tracywalker** [comment]
Yes, it looks like that hover tooltip has been removed in latest Fx Beta.  If you comment out lines 52-57, does the test work?  If so, please remove those lines from the test.

**Comment by tracywalker** [comment]
Actually the tool tip is still there. You have to hover the magnifying glass and the tooltip is reduce to "Search"  The assert for the hover message is unnecessary. As such it is probably safe to just remove the offending exists/assert from the Iris test.  It is only there to confirm the search bar is present. Just hovering the search bar isn't any guarantee that the search bar actually has focus.

**Comment by ranjit-exalt** [comment]
After removing the assert to check "Search using Google" text, this blocker issue is resolved. There are a couple of more fixes needed in this test case but those are not related to the current issue, hence closing this issue.
