### ISSUE TITLE
Default search engine list is re-ordered *only* in Iris

### ISSUE THREAD

**Issue by ashughes1** [mozilla/iris_firefox#4235]
The antivirus/firefox_hijacking_default_search test is failing on Linux because the pattern it's looking for is the vertical section of favicons for the search engine list in about:preferences#search in the Default Search engine picker.

By default the list places Google first then alphabetical ordering for the rest, however when the test restarts Google is placed alphabetically which is not what should be happening. Since the ordering of the icons has changed the pattern fails to match. This behaviour is not reproducible manually.

*Correct*
![fx_default_search_correct](https://user-images.githubusercontent.com/766595/69194036-053aa100-0add-11ea-83f0-ad8606f7ab5e.jpg)

*Incorrect*
![fx_default_search_incorrect](https://user-images.githubusercontent.com/766595/69194070-171c4400-0add-11ea-8046-bbe58b7e6c09.jpg)

**Comment by tracywalker** [comment]
Not going to bother with investigating this.  I'm going to archive this entire test group.  Anthony, I'll ping you later to explain.
