### ISSUE TITLE
Investigate and fix Travis CI

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris_firefox#4243]
Recent PR's to dev are getting failed build reports from Travis Ci.   ie. https://github.com/mozilla/iris_firefox/pull/4241/checks . The branches for the PR's run fine locally.

**Comment by tracywalker** [comment]
Team, for now, please ignore the Travis failures in your PR's to dev.  Some things seem to be mixed up in which repo's are running what.  see bug https://bugzilla.mozilla.org/show_bug.cgi?id=1598454

When that bug is fixed we can confirm and close this issue.

**Comment by tracywalker** [comment]
Matt, if that bug takes long to get resolved, can this just be disabled in iris_firefox?

**Comment by kimberlythegeek** [comment]
I could try maybe deleting the `.travis.yml` file, merge that change, and then add it back? I'm really unsure. There is no way for a user to remove a repo from Travis without deleting the repo:
https://github.com/travis-ci/travis-ci/issues/987
