### ISSUE TITLE
Download logic on Windows 10 is not respecting browser.download.dir

### ISSUE THREAD

**Issue by ashughes1** [mozilla/iris_firefox#4252]
On Windows 10, the `download_pdf.py` test in In Browser PDF is not respecting the browser.download.dir preference that's set at the beginning of the test. I'm not sure yet if this applies to other downloads tests but when running the test I can see the PDF download to the system-level default download folder, ie. `C:\Users\Iris\Downloads` instead of `C:\Users\Iris\.iris_firefox\<run_ID>\downloads`. At this time the test fails and as a result the test doesn't clean up the downloads properly.

**Comment by ashughes1** [comment]
I've noticed that this is reproducible with any test that downloads a file. The tests change the default Download folder to one local to the Iris testrun folder but files still download to the standard default folder instead. I suspect this might be causing some test failures but it also means the downloaded files don't get cleaned up because the cleanup logic points the the Iris download folder instead of the default.

**Comment by tracywalker** [comment]
Matt, can you take a look at this next week?

**Comment by ranjit-exalt** [comment]
Many of the test cases for "download_manager" test suit is also failing due to the download path issue. For example, "about_downloads_accurate_data.py" is failing across all platforms as it's downloading the file in the local download folder. An empty download folder is getting created at C:\Users\Iris\.iris_firefox\<run_ID>\downloads

Tagging download_manager parent issue (#4271 ) for tracking.

**Comment by mwobensmith** [comment]
I have isolated the problem - it's a core bug that I introduced a few weeks ago. I will fix it ASAP.

See [core issue 653](https://github.com/mozilla/iris/issues/653).

**Comment by mwobensmith** [comment]
Also, once this is fixed, I believe there will be other issues with these tests unrelated to this bug. I have seen some incorrect patterns, for instance, that will need to be updated.

**Comment by mwobensmith** [comment]
@tracywalker If this is working now, feel free to close.

**Comment by ranjit-exalt** [comment]
This is working fine for me.
