### ISSUE TITLE
Block unstable tests

### ISSUE THREAD

**Issue by spronoza** [mozilla/iris_firefox#4283]
[Link to the list of the blocked tests](https://docs.google.com/spreadsheets/d/10Cj5xeoWdcr2b2oox3sUczvqGj_ESMQO6dazgEwqM_w/edit?usp=sharing)

**Comment by tracywalker** [comment]
I don't want all the tests disabled based on just this one issue.  I want a new issue opened for each failing test. Then the blocked_by should point to the individual issue. If, for this initial set of failing tests, you want to commit all the changes in one PR for this bulk issue, that is fine, as long as each disabled test case has its own issue.  I'll explain a bit more in the meeting shortly.
