### ISSUE TITLE
"option_list" dictionary in open_hamburger_menu(option=None) have wrong key value pair if "Restore Previous Session" is disabled

### ISSUE THREAD

**Issue by ranjit-exalt** [mozilla/iris_firefox#4337]
https://github.com/mozilla/iris_firefox/issues/4257 : When the "Restore Previous Session" option is disabled in the hamburger menu, the number of times down key (or Tab) press is getting decreased by 1. So, there should be a conditional check for the active-inactive status of the "Restore Previous Session" option in open_hamburger_menu(option=None). 

When the "Restore Previous Session" option is enabled, the dictionary should be: 
option_list = {'Restore Previous Session': 5,
                     'Customize': 14,
                     'Print': 17,
                     'Web Developer': 20,
                     'Help': 22,
                     'Exit': 23,
                     'Quit': 23}

And when it's disabled, the revised dictionary should be :
option_list = { 'Customize': 13,
                   'Print': 16,
                   'Web Developer': 19,
                   'Help': 21,
                   'Exit': 22,
                   'Quit': 22}

clear_download_preview_panel.py test case is failing due to this issue. The parent issue of this test case is https://github.com/mozilla/iris_firefox/issues/4271.

**Comment by tracywalker** [comment]
Dimtry changed this helper to use patterns for each option.  His work is in dev branch.
