### ISSUE TITLE
On clicking "Open Containing Folder" icon, the folder is not opening in the foreground - Linux

### ISSUE THREAD

**Issue by ranjit-exalt** [mozilla/iris_firefox#4383]
For the Linux machine, on clicking the "Open Containing Folder" icon, the folder is not opening in the foreground. It's opening in the background while the Firefox browser is still displaying in the foreground. 

For all other operating systems, it's working fine. 

Following test case has been marked as blocked: 
        test_case_id="[99481](https://testrail.stage.mozaws.net/index.php?/cases/view/99481)",
        test_suite_id="1827"

Linking issue #4271 for tracking.

**Comment by MarisBogdan** [comment]
From what we know this is an old issue, older than Fx40 after doing a manual check. My colleagues told me that there is a bug somewhere in bugzilla but I was unable to pinpoint its number so I think we can log a new one and someone who takes care of downloads component could help tracking down that one. I've logged bug 1606295 in bugzilla.

**Comment by ranjit-exalt** [comment]
Adding Bugzilla bug URL for defect tracking: https://bugzilla.mozilla.org/show_bug.cgi?id=1606295
