### ISSUE TITLE
Pause-unpause not working for test site - Linux 

### ISSUE THREAD

**Issue by ranjit-exalt** [mozilla/iris_firefox#4386]
For the Linux OS, When the user pauses the download and then resumes the download from Localhost ('http://%s:%s/thinkbroadband/' % (_ip_host, _port)) or test site (https://irisfirefoxtestfiles.netlify.com), download is getting Failed. On clicking "Resume", it should start downloading. 

Following test case has been marked as blocked: 
        test_case_id="[99471](https://testrail.stage.mozaws.net/index.php?/cases/view/99471)",
        test_suite_id="1827",

Linking issue #4271 for tracking.

**Comment by mwobensmith** [comment]
@tracywalker Who would own this?

**Comment by tracywalker** [comment]
At a glance I think this is likely just timing in the test case vs download.  Investigation needed.  Ranjit, since you have been working on these download tests, please assign to yourself.

**Comment by ranjit-exalt** [comment]
> At a glance I think this is likely just timing in the test case vs download. Investigation needed. Ranjit, since you have been working on these download tests, please assign it to yourself.

I have investigated this. It's not related to timing or throttling. You can reproduce this issue manually by following given steps: 

1. Open https://irisfirefoxtestfiles.netlify.com
2. Click any of the download file icons (for example: "Very Large File (1GB)").
3. Select the "save file" and click the "ok" button.
4. Click on browser download icon (CTRL+SHFT+Y).
5. Once download starts, right-click on download progress file and click on "pause".
6. File download paused. Here, it's working as expected. 
7. Again, right-click and click on "Resume" 
8. Download should be resumed, but after waiting for some time, download is getting Failed.

The same issue is occurring with the local web as well.
