### ISSUE TITLE
CTRL+SHFT+A not working in Linux: New private window

### ISSUE THREAD

**Issue by ranjit-exalt** [mozilla/iris_firefox#4422]
On the first time, Firefox (Beta) installation, If the user opens a new private window and click on CTRL+SHFT+A, "about:addons" page does not open. 

![Linux_menu_private_window](https://user-images.githubusercontent.com/54833244/71018162-fd8f0c00-211d-11ea-8955-62b48e1de9bf.jpeg)

It starts working fine if the user clicks on the menu [≡] → Add-ons, next time onwards, the shortcut key started working. 

It's working fine on Mac and Windows. 

Since in Automation test, every time a fresh browser launches, the test case is getting failed. 

Blocked Test case: https://testrail.stage.mozaws.net/index.php?/cases/view/15266 (Issue #4338 )

**Comment by MarisBogdan** [comment]
I tried this scenario manually on two Linux machines (Ubuntu 18.04 and 16.04) using Firefox 72.0b8 and it works for me every time I hit Ctrl+Shift+A.

**Comment by ranjit-exalt** [comment]
> I tried this scenario manually on two Linux machines (Ubuntu 18.04 and 16.04) using Firefox 72.0b8 and it works for me every time I hit Ctrl+Shift+A.

I can reproduce it on Ubuntu 16.0 (Firefox 72.0b8). Please follow the following steps to reproduce this: 

1. Uninstall previously installed Firefox. 
2. Install firefox beta.  
3. Launch Firefox and open a new private window.
4. Press Ctrl+Shift+A.

This issue only occurs in the above scenario. If you have ever opened add ons on firefox, Ctrl+Shift+A will work perfectly.

**Comment by MarisBogdan** [comment]
I followed your steps again, only tried with fresh new profiles/installs so about:addons was not opened before on that session, still works for me on both Ubuntu 16.04 64bit and 18.04 64bit.

**Comment by ranjit-exalt** [comment]
CTRL+SHFT+A still unable to launch "about:addons" page during automation run for "new private window" in Linux. So implementing this with an alternate approach, i.e. launch "about:addons" page by clicking "Add-ons" from the hamburger menu.

**Comment by ranjit-exalt** [comment]
The issue merged, hence closing.
