### ISSUE TITLE
Fix keyboard_shortcuts_work_in_search_bar

### ISSUE THREAD

**Issue by dbakaev** [mozilla/iris_firefox#4426]
Need to fix keyboard_shortcuts_work_in_search_bar test failing on the following platforms:
- win10
- win7
- linux

I've attached run results from this platforms. Use them if needed.
[win7.zip](https://github.com/mozilla/iris_firefox/files/3984063/win7.zip)
[win10.zip](https://github.com/mozilla/iris_firefox/files/3984064/win10.zip)
[osx.zip](https://github.com/mozilla/iris_firefox/files/3984286/osx.zip)

Test is blocked until it will be fixed.

**Comment by ranjit-exalt** [comment]
Code Merged. Closing Issue.
