### ISSUE TITLE
Investigate download_cancel_retry.py not running in firefox target

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris_firefox#4451]
The test download_cancel_retry.py doesn't get run in firefox target. Other tests in the download manager group run correctly and this test runs correctly in nightly target.  Please investigate why.

**Comment by tracywalker** [comment]
Matt, can you take a look at this? Results in Control Center are showing success in duration less than 1 second.  And the isn't any useful info in the log.

**Comment by mwobensmith** [comment]
The problem is in your imports. Look at the top of `download_cancel_retry.py` and see which target you are importing from. This is a `firefox` test but it's trying to import from `nightly` and that doesn't work. Just change the imports to this and you'll be fine:

```
from targets.firefox.firefox_ui.helpers.download_manager_utils import *
from targets.firefox.fx_testcase import *
```

**Comment by tracywalker** [comment]
Thanks for taking a look, Matt. Something simple, as I suspected.
