### ISSUE TITLE
Fix search_code_yandex

### ISSUE THREAD

**Issue by ranjit-exalt** [mozilla/iris_firefox#4490]
Test script failed in all OS.

error: AssertionError"
message: Client search code is correct for searches from awesomebar, region RU.

**Comment by tracywalker** [comment]
They have changed the construction of the search results url.  
 
I'll fix this test.

**Comment by ranjit-exalt** [comment]
This Issue is reproducible again after the latest UI changes, hence Reopening the Issue.
The test script failed in all OS.

Error: AssertionError
Message: Client search code is correct for searches fromawesomebar, region RU.
