### ISSUE TITLE
UI glitch in bookmark properties header in Linux

### ISSUE THREAD

**Issue by ranjit-exalt** [mozilla/iris_firefox#4613]
In Linux, when user clicks on library menu -> bookmarks -> right-click on (About Us) -> Properties, the double quote in properties header ( Properties for "About Us" ) is not displaying correctly.  Screenshot and steps to reproduce mentioned below: 

OS: **Linux 16.04 LTS**
Firefox version: **73.0b9**
Affected test case: https://testrail.stage.mozaws.net/index.php?/cases/view/165492 

**Steps to reproduce:** 
1. Click on library menu -> bookmarks.
2. right-click on "About Us" or "Get Involved".
3. click on Properties.
4. Verify the properties header.

![image](https://user-images.githubusercontent.com/54833244/73191263-3672c580-414d-11ea-8581-3d4a85b96190.png)

**Comment by tzsoldos** [comment]
I could not reproduced this issue following steps mentioned above, tested on Ubuntu 16.04 x64 using Firefox 73.0b9, tried with every menu item from Library -> Bookmarks -> Recently Bookmarked, right click on this, then click on properties, every time the header is correct, no UI glitch in bookmark properties header. Am I misssing something?

**Comment by ranjit-exalt** [comment]
I can reproduce this issue on 73.0b10 as well on Ubuntu 16.04 x64. For better understanding, I have recorded the steps to reproduce. Please click on the given link to see the video demonstration. 

https://drive.google.com/file/d/1UCdwB8UtlpC07hgZCYBUbVlpRTusVhII/view?usp=sharing

**Comment by tracywalker** [comment]
I cannot reproduce this.  It seems like something local to Ranit's system.
