### ISSUE TITLE
[Linux] Set as default window the window where the browser opens 

### ISSUE THREAD

**Issue by icrisan** [mozilla/iris_firefox#92]

**Comment by mwobensmith** [comment]
Dual monitor scenario - use the window where the browser opens for all image/text search.

**Comment by tracywalker** [comment]
I think we do not need to support dual monitor for 1.0.

**Comment by silviuFlorin** [comment]
@mwobensmith With the new Screen class implementation we are able to retrieve monitor/s details. 
Right now we are defaulting to the primary monitor and assume Firefox will open there. To fully support the case where Firefox opens on secondary monitors we will need additional checks. We should also support cases where one monitor is High Def and the other is not. 
All the above cases are relatively easy to implement.

**Comment by mwobensmith** [comment]
@silviuFlorin Agreed. If you don't mind, I'm going to assign to you since you are probably the most knowledgeable about the topic at this point. 😉

**Comment by mwobensmith** [comment]
Out of scope for now, will revisit if it becomes a priority.
