### ISSUE TITLE
Use Firefox source tree assets directly in Iris

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris_firefox#921]
For 1.0, we are implementing #647 to handle our basic UI and pattern needs. However, in the future, we'd like Iris to be able to sync to source tree assets dynamically.

We might do this:

* Clone the Firefox source tree locally.

* Inspect directories that contain UI assets, mainly:

/browser/themes/

For instance, the "home" icon is here:

/browser/themes/shared/icons/home.svg

* Run a script on the directory above to extract all PNG and SVG files, and copy them to a new location inside Iris, while preserving the directory structure.

* Convert SVG to PNG.

* Update our Firefox UI classes so that the constants now point to the new assets. Note that we should be able to create a `Pattern` from an image nested inside a subdirectory. 

```
class NavBar():

    # resolve this path relative to this module's image directory
    HOME = Pattern('/shared/icons/home.png')
```

This will have to play well with our work for #590. When creating a `Pattern`, it will resolve the path to the image using a string, and be flexible enough to work with paths, both relative and absolute.

**Comment by tracywalker** [comment]
I believe this is beyond the scope of what we're capable of doing.  The SVG images in the code base are only one layer of what is actually rendered on screen.  In addition to fetching the SVG's and converting them to png's, we would also have to identify what the correct background is and piece the two together.  I don't see our project having the resources to tackle this anytime soon. As such, I am marking this issue won't fix.  If resources along with a good idea how to do this become available, we can revisit/reopen this issue.
